### ISSUE TITLE
How to install on Linux

### ISSUE THREAD

**Issue by golinmarq** [sqlectron/sqlectron-gui#107]
I downloaded the .zip file, unziped but I don't know what to do now. I'm a new Linux user, sorry the silly question

**Comment by maxcnunes** [comment]
You can execute the binary file directly from there. But usually on linux is recommended to move the application directory into the [`/opt`](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html) directory.

**Comment by golinmarq** [comment]
Thanks!
