### ISSUE TITLE
Typography in database list

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#108]
I agree with [statement](https://github.com/sqlectron/sqlectron-gui/commit/d29355e874c83f4ddcf9ef63939d02b7b7e9f39d) that previous style was using too small font, but current setup makes it look weird, like database metadata titles have bigger font (although they don't) than databases names because they are weighted. Since they are sub list, maybe its better to make them normally weighted. Or put database names in bigger font. Also, maybe currently active databases should be bold.

Issue is here so we can discuss it since its more matter of UX.

**Comment by maxcnunes** [comment]
Sure. I was not totally fine with this result. But it was already better than the previous one.
What do you think about this attempt?
![screen shot 2016-04-11 at 7 05 55 am](https://cloud.githubusercontent.com/assets/680356/14423781/fb35f19c-ffb3-11e5-93b6-259e3f8404ac.png)
It uses the same font-size of the children and has a collapse icon.

**Comment by BornaP** [comment]
Yeah this one looks much better. Collapse icon should definitely stay.

Maybe children items should have indention, so it feels more like they are children of item above them. I think its a best practice when it comes to this tree structures. Probably adding left padding would do the trick, so that children items are aligned with first/second letter of parent node.

**Comment by maxcnunes** [comment]
Cool. I'm gonna try that later today then. I hope finish it today, to release a new version. It's been a while since the last release.

**Comment by maxcnunes** [comment]
I have included a margin left for the menu. And also changed the color of the metadata titles to have a bit of less attention than the database title.
![screen shot 2016-04-11 at 7 55 45 pm](https://cloud.githubusercontent.com/assets/680356/14444935/74bcd7e0-001f-11e6-8eec-1a316a31abb7.png)

**Comment by BornaP** [comment]
Great, this looks much better now :+1:
