### ISSUE TITLE
Table rows are not rendered in matching table headers in query result table

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#111]
I just tried sqlectron with one bit bigger database (~130 tables) and executed default query on one of the tables (double-clicked table name). What I noticed is that all data is fetched correctly, but they are rendered under wrong table headers. They are mixed completely randomly. However, inspecting the elements I noticed that under data-reactid attribute correct column was set.

Here's example:

![sqlectron_result](https://cloud.githubusercontent.com/assets/8470710/14433312/1f1acc40-000e-11e6-97d1-302d3686ad60.png)

These attributes in <> (<name> ...) should be under column named `contentobject_name` , but they are rendered under `sort_order`. Element attribute `data-reactid` seems to have right column at the end.

**Comment by BornaP** [comment]
Seems bug only occurs when table has more than 15 columns.

**Comment by maxcnunes** [comment]
That is weird. Let me know if you need help with it.
