### ISSUE TITLE
Filter database metadata items

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#114]
I have some databases that have too many tables. Would be awesome if was possible to filter the metadata items.

**Comment by BornaP** [comment]
Good idea! Search filter should probably be placed somewhere under the 'Tables' header.

If this will be implemented, and having in mind we might fetch & list table columns/triggers (on a click on single table) in future, maybe it's good idea to make side menu bit wider after implementing this.

I can jump on this after resolving #111

**Comment by maxcnunes** [comment]
I thought in 3 options:

A. change the database search to include some filters. This way would have a global search. (Would be applied only in the loaded data. e.g. If a database is not connected, would not be possible to search for its tables).

**Initial state:**
```
_Search database..._ [search][+]
```
**After clicking in the [+]:**
```
_Search database..._ [search][+]
_Search table..._
_Search views..._
_Search functions..._
_Search procedures..._
```
> The items with underscore are the fields and with brackets are the buttons :laughing: 

B. Include the search over `Tables`. Which would search for any matada in that database. (I like the simplicity of this one and is already enough for me).

C. Include the search under all metadata headers. (I think this is not necessary)

**Comment by BornaP** [comment]
Although A is quite interesting solution, I also fancy option B. It's simple, has one step less than A (which is better) and get's the job done :)

**Comment by BornaP** [comment]
I'll probably make PR for this tommorow.
