### ISSUE TITLE
Username/password only updated after restart

### ISSUE THREAD

**Issue by AndiDog** [sqlectron/sqlectron-gui#116]
So I've happily tried sqlectron the first time after seeing it on reddit. Nice job!

My issue can be reproduced like this:
- Add MySQL server and enter wrong username/password
- Save (which closes the dialog) and connect. That will give an "access denied" error.
- Edit the connection again and correct username/password values
- Save and try to connect again. This **still** gives an error, but should of course connect successfully. Note that the "Test" button in the connection edit dialog does the right thing (connection works).

Using sqlectron 1.5.0 from homebrew cask.

**Comment by darkwisperer** [comment]
@AndiDog Good catch!

I can confirm this issue also affects mssql

**Comment by maxcnunes** [comment]
Thanks @AndiDog. I will fix it later today.

**Comment by maxcnunes** [comment]
I could not reproduce this bug. Maybe is something that have been fixed already by another change. Could you teste it in the new version (v1.6.0)?

**Comment by maxcnunes** [comment]
@AndiDog and @darkwisperer could you confirm if it really still happening?

**Comment by darkwisperer** [comment]
@maxcnunes  This issue is resolved in 1.6.2

**Comment by maxcnunes** [comment]
@darkwisperer sorry, I didn't quite understand. Did the windows installer of 1.6.2 work for you? What in the installer was glitched out and unreadable?

**Comment by AndiDog** [comment]
Issue is resolved.
