### ISSUE TITLE
Grid is converting the date when showing the data

### ISSUE THREAD

**Issue by mayconbeserra** [sqlectron/sqlectron-gui#117]
The grid is converting the date when it should not.

Based on my query, the result is different from my date range.
![image](https://cloud.githubusercontent.com/assets/911493/14536176/7bd6cea8-0247-11e6-90a0-dc1c55b6a1f1.png)

**Comment by krolow** [comment]
what is the db that you are using @mayconbeserra could not reproduce in pgsql at least i get the results that were expected

**Comment by mayconbeserra** [comment]
Hi, It is happening on mySql. I have installed SQLelectron this week.

**Comment by krolow** [comment]
alright @maxcnunes mention that might be related with timezone conversion i'll leave to him check

**Comment by maxcnunes** [comment]
The best approach would be not parsing the data from the DB to nodejs. Which all the sql clients does by default.
The Mysql client has a configuration `typeCast` for that. But seems PG and MSSQL does not have that configuration available. I don't have much time for that right now. So any PR is well come 😄
