### ISSUE TITLE
Query auto completion

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#120]
Having in mind recent [feedback from redit](https://www.reddit.com/r/programming/comments/4en0jh/sqlectron_one_single_db_client_for_any_relational/d22og0t) and feedback I'm getting from others, this should have it's own issue.

It would be a major enhancement for the app if query box would have auto completion (existing tables, columns, etc.). I haven't checked if ace editor comes with API which could be used for this feature (if it does not there are alternatives like [CodeMirror](https://codemirror.net/)).

**Comment by maxcnunes** [comment]
Yeah. That would be an awesome feature. I don't have much time to implement it right now. But if you are  interested in implementing it. Please do. Let me know if you need help in anything.
By the way. Looks like ace has support for auto complete - https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor.

**Comment by darkwisperer** [comment]
Autocomplete would be amazing!

**Comment by BornaP** [comment]
Although issue was resolved with this [commit](https://github.com/sqlectron/sqlectron-gui/commit/55f5894a0f261cfcf3a544a3df30da016bf4e1be), I'll leave this issue open for further discussion on autocomplete enhancement. 

As mentioned in  #128 , both basic and live autocompletion should be optional (hence user should be able to enable and disable it). Furthermore, there's way to include tables and columns in autocompletion by writing custom completer, explained [here](https://github.com/securingsincity/react-ace/issues/69).

**Comment by maxcnunes** [comment]
The metadata is now loaded into the auto completion list. I guess is just missing apply the custom configurations to consider this task done. I can work on that tomorrow.

**Comment by maxcnunes** [comment]
Completed with https://github.com/sqlectron/sqlectron-gui/commit/a50497c79ba6bfed1e856f4aea1fe73c132e48d2
