### ISSUE TITLE
The App Crashes On Launch

### ISSUE THREAD

**Issue by insha** [sqlectron/sqlectron-gui#121]
The app (latest 1.6.0) when launched crashes with the following message:

<img width="532" alt="screen shot 2016-04-17 at 11 51 30 pm" src="https://cloud.githubusercontent.com/assets/1245047/14595859/5b0b5a38-04f7-11e6-8f79-a359513b89b6.png">

OS X: 10.11.4

**Comment by maxcnunes** [comment]
Thanks @insha. I am working on it.

**Comment by maxcnunes** [comment]
Fixed in the version 1.6.1. Could you please check if it works for you?

**Comment by darkwisperer** [comment]
Here is the error for 1.6.1 on windows:
![image](https://cloud.githubusercontent.com/assets/740476/14609987/e9b47f8c-0540-11e6-83b2-93b81b910032.png)

**Comment by insha** [comment]
That worked! Thanks 👍
