### ISSUE TITLE
Uncaught exception in windows installer

### ISSUE THREAD

**Issue by hardliner66** [sqlectron/sqlectron-gui#122]
When I try to install on my windows machine (win 10 64 bit) I get an uncaught exception:
"Cannot find module 'babel/polyfill'"

![image](https://cloud.githubusercontent.com/assets/2937272/14595937/388499c4-0543-11e6-86ab-9811fe47a087.png)

**Comment by maxcnunes** [comment]
Thanks @hardliner66. I am working on it.

**Comment by maxcnunes** [comment]
This only occurs on windows. I will fix it later today.

**Comment by darkwisperer** [comment]
I can confirm this issue on windows 7

**Comment by maxcnunes** [comment]
Reason why the release for windows is not working - https://github.com/electron-userland/electron-builder/issues/336.
But I still trying to fix it.

**Comment by maxcnunes** [comment]
@hardliner66 or @darkwisperer could someone test it with the version 1.6.2?

**Comment by hardliner66** [comment]
I just tried it and it works now.

**Comment by kbradl16** [comment]
1.6.2 works for me as well on Windows 10 64 bit
