### ISSUE TITLE
Ability to describe Table as SQL

### ISSUE THREAD

**Issue by eMerzh** [sqlectron/sqlectron-gui#125]
It would be cool to have the ability to view the tables (or any object btw) as SQL
to be able to understand what type of data is it, what are the limits , indexes, ...

**Comment by BornaP** [comment]
You mean like getting SQL definition of table/procedure/view? If so, I had something like that in mind. Definitely something we will implement in foreseeable future I guess!

**Comment by eMerzh** [comment]
Yes exactly that :)

**Comment by krolow** [comment]
yes, +1 for the feature, i was also thinking in implement that, it would be nice to have it

**Comment by BornaP** [comment]
Resolved with #141
