### ISSUE TITLE
Table rows scaling

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#126]
I noticed that because of some long text (nvarchar) attributes, table rows do not scale nicely, they become too big. For example:

![table-sqlectron](https://cloud.githubusercontent.com/assets/8470710/14811590/03f188a0-0b99-11e6-8a5a-115bbed076b8.png)

Trying the same example with other DB tools, I realized they mostly do not allow word breaks and instead limit column width to certain number of chars (somewhere between 20 and 30 I guess). After certain number of chars shown, '...' is appended. If someone wants to see whole string, column width can be resized manually (also double clicking the columns selects whole text). Here's screenshot from MySQL Workbench, but MSSQL Server managment studio works the same 

![table_workbench](https://cloud.githubusercontent.com/assets/8470710/14811740/ce08ae52-0b99-11e6-976d-b7b94afbb785.png)

I think second way of scaling long strings/texts is much more convenient, as it reduces need for scrolling as more rows are shown within the same window.

**Comment by krolow** [comment]
I think it's good, i like the approach of open a modal with a full text view in case of double click what do you think?

**Comment by BornaP** [comment]
I thought about just selecting the whole text (so user can copy it), but I think modal would be fine :)
