### ISSUE TITLE
Create a settings page/window

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#131]
I guess few users now how to use the custom configurations with the `.sqlectron.json`.
A settings page would be much easier for any user customize that configurations.

**Comment by maxcnunes** [comment]
@krolow do you mind implementing it? 😄

**Comment by krolow** [comment]
leave to me I can work on that a long of this week for sure

**Comment by maxcnunes** [comment]
Awesome. No rush 💃

**Comment by maxcnunes** [comment]
Hey @BornaP, are you working on this one? I could take it otherwise.

**Comment by BornaP** [comment]
@maxcnunes Ah sorry, I self-assigned it, but something else kicked in later. Forgot about it. If you have time to work on this one, feel free to reassign it. :)

**Comment by maxcnunes** [comment]
Implemented at https://github.com/sqlectron/sqlectron-gui/pull/358
