### ISSUE TITLE
Be able to resize font at query editor

### ISSUE THREAD

**Issue by krolow** [sqlectron/sqlectron-gui#137]
![image](https://cloud.githubusercontent.com/assets/46822/15120419/02db3a1c-15ec-11e6-8137-14e3413dd523.png)

Default font-size it's too small, it would be good to be able to resize the font (at least use ctrl + scroll, to increase the font-size)

**Comment by BornaP** [comment]
Closed with 33548c93aa445639bb010f362c58396257554d67
