### ISSUE TITLE
Upgrade to electron 1.0

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#142]
Title says it all. Electron's first major is here! :tada: :confetti_ball:  [Electron 1.0](http://electron.atom.io/)

@maxcnunes Since you're the initiator of the Sqlectron, probably you are the best person to make PR and include Sqlectron on [Electron Apps page](http://electron.atom.io/apps/). Here's [how to do that](https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site). \o/

**Comment by maxcnunes** [comment]
Awesome. I have sent the PR including Sqlectron to the list of apps.
Lets upgrade!!! We just have to be careful and test well. Because we had some problems with the latest attempts to upgrade the electron.

**Comment by BornaP** [comment]
I've spent some time trying to get this working but I think we will have to wait a bit with this. There's definitely problem with newer electron version handling `Promise.reject` from remote. Error gets swallowed and cannot be caught (for example [here ](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/actions/queries.js#L169)). It might be correlated to newer Chromium versions since on v0.37.0 it was upgraded to Chrome 49, and last working version for our case is still 0.36.12. There's issue opened for this in April and marked as bug. [Check it out](https://github.com/electron/electron/issues/5111). Hoped it would be solved in new major release but well...
That being said, and having in mind a lot of our calls on back-end API depend on Promise resolve/reject, I'd stick to 0.36.12 and wait for updates on this bug. However, I'll open PR with changes for easier upgrade (since old way of requiring electron modules is deprecated and not supported in v1.x).

**Comment by maxcnunes** [comment]
Sure. Lets wait until that error has been resolved.

**Comment by BornaP** [comment]
Issue has been [resolved](https://github.com/electron/electron/pull/5666), so I'll wait for new release (that includes this changes) to check it out if it works :)

**Comment by BornaP** [comment]
Close via #169
