### ISSUE TITLE
Replace paging result with "scrolling" result

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#144]
After implementing #126 will be possible to use a "scrolling" result (because requires a fixed height for rows). Which I guess gives a much better UX. What do you think guys?

This one looks really good: https://facebook.github.io/fixed-data-table/.

**Comment by BornaP** [comment]
I like the idea, big thumbs up for this! It looks much more 'native' for this kind of app. I'll try to implement #126 as soon as possible!

**Comment by krolow** [comment]
it looks good this fixed data table
