### ISSUE TITLE
Improve documentation about shortcuts

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#150]
Would be good have a page listing all available shortcuts.
The app already has few shortcuts and the ace editor also has some good [shortcuts](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts).
I was thinking in keep it simple and just adding a link in the app to a webpage which could be a markdown file in the repository or even a page in the wiki (which we don't have yet).

What do you guys think?

**Comment by BornaP** [comment]
I agree on adding this! Link to the markdown file sounds good enough, but if you were thinking about creating a wiki page anyway, then that would be a better solution! :)

**Comment by maxcnunes** [comment]
Ok, so a wiki it will be 😄
