### ISSUE TITLE
Add support to ssh tunnel with key using password

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#155]
I just confuse which one is the better approach:

* save the password in the configuration (is easier, and we already does that for other passwords)
* show a modal during the ssh connection asking for the ssh key password

**Comment by BornaP** [comment]
I'm not really using this much, but I think ssh key pass phrase should not be stored as a plain text in configuration, because what's the essence of using _secure_ tunneling then. So prompting user on connection for pass phrase would be better approach I guess.

**Comment by maxcnunes** [comment]
Neither do I. Although there are people that sure use that. Yeah the modal is the correct way 👍

**Comment by BornaP** [comment]
Haha I know, it's really useful feature :smile: I meant in a way that I might be wrong as I'm not using it regularly. But I'm glad you too agree on modal :smile:
