### ISSUE TITLE
ssh connection error

### ISSUE THREAD

**Issue by plandevida** [sqlectron/sqlectron-gui#167]
Hi,

I tried to configure a connection over ssh configuration, that is the same I'm using with mysql workbench, but it's fails showing "_Connection refused_".

The connection works:
```
nc 192.168.2.5 22
SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u2

ssh root@192.168.2.5
root@192.168.2.5's password:
Last login: Tue May 24 08:41:19 CEST 2016 from 192.168.2.103 on pts/3
Linux  #1 SMP Debian x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@Debian:~#
```

**Comment by maxcnunes** [comment]
That is weird. Most of the connections I use are over SSH. Could please include this sqlectron server configuration `~/.sqlectron.json`.
**Important**: replace the values that are secret such as host, database, user, password with `secret`.
Also what is the OS and the sqlectron version are you running?

**Comment by plandevida** [comment]
Hi,

I'm using Ubuntu Linux 16.04 and SQLElectron 1.8.0

[sqlectron.json.txt](https://github.com/sqlectron/sqlectron-gui/files/279282/sqlectron.json.txt)

**Comment by maxcnunes** [comment]
Hi @plandevida,

Looks like you have not configured the connection to use the SSH Tunnel.
Here is an example:
![screen shot 2016-05-24 at 7 53 53 am](https://cloud.githubusercontent.com/assets/680356/15501607/ce1eb7a0-2184-11e6-8328-ce03e563a064.png)

Could you test that and let me know if it works?

**Comment by plandevida** [comment]
I did it
![example](https://cloud.githubusercontent.com/assets/1167738/15501983/5d1d046c-21b1-11e6-9bd3-12750bb049ab.png)

**Comment by maxcnunes** [comment]
Ok. I have found the problem. The test connection with SSH Tunnel is not working without saving the configuration. Try to save it then connect. It should work.

**Comment by plandevida** [comment]
hi, now work, thanks.

**Comment by lordloh** [comment]
I am using 1.15.0 and I am having the same problem and saving the connection does not help to either test or to actually connect. I have this problem on Windows, The linux installation seems to work fine.

**Comment by lordloh** [comment]
Deleting the connection and creating a new one with the exact same configuration worked!

**Comment by maxcnunes** [comment]
Weird. In case it occurs again, please try to find on `~/.sqlectron.json` the configuration for the problematic connection and include that in the issue (change secret values before that). That might help find what is the problem.

**Comment by SapioBeasley** [comment]
I received this error when the incorrect RDS DB server address was input. Maybe a different error message should be displayed to differentiate the two?
