### ISSUE TITLE
I can't open in on mac os 10.11

### ISSUE THREAD

**Issue by CommanderXL** [sqlectron/sqlectron-gui#177]
Well. I can't open the gui. My mac os is 10.11 and I download Sqlectron-1.8.0-mac.zip

**Comment by maxcnunes** [comment]
Hi @CommanderXL,

My Mac is `10.11.4`. I have tested both `Sqlectron-1.8.0-mac.zip` and `Sqlectron-1.8.0.dmg` and they are working properly for me.

Have you tried the `Sqlectron-1.8.0.dmg` as well?

Is there any error message on opening the app?

**Comment by CommanderXL** [comment]
Yeah.I have tried Sqlectron-1.8.0.dmg , it can't as well.

Does it look like the mac os  must be 10.11.4 ?

**Comment by maxcnunes** [comment]
I dont think that. There is a guy at my office that uses  Mavericks version and sqlectron works for him.

Maybe is not running because you have not allowed apps from unidentified developer. Could you check that?

**Comment by BornaP** [comment]
@CommanderXL Have you tried what Max suggested, allowing apps from unidentified sources? Or running version 1.9.0?

**Comment by maxcnunes** [comment]
Since I have not heard of you in almost a month I going to close this issue. I hope that has worked for you. Otherwise, please just re open this issue.
