### ISSUE TITLE
no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by safinn** [sqlectron/sqlectron-gui#178]
Trying to connect to a PostgreSQL database using 1.8 mac, I get the error `no pg_hba.conf entry for host...`. I tried a different client and it managed to connect fine. The database is the free Heroku PostgreSQL one.

Any ideas?

**Comment by maxcnunes** [comment]
Looking in these error on [stackoverflow](http://stackoverflow.com/questions/17377118/heroku-database-connection-properties) seems you have to connect over HTTPS. Try to enable the `SSL` option on sqlectron server connection.

**Comment by safinn** [comment]
I have enabled SSL using the toggle. I also double check in the `.sqlectron.json` file and the server has `"ssl": true,` but still getting the same issue.

**Comment by maxcnunes** [comment]
I just remembered there was a bug not setting the SSL attribute on PG connections. It was fixed [here](https://github.com/sqlectron/sqlectron-core/issues/16). But we have not released a new version after that. I'm planing in release it this week. Sorry for the trouble.

**Comment by safinn** [comment]
Perfect. I'll wait for the update. Thank you for your help.

**Comment by maxcnunes** [comment]
The new version with the fixing for this bug was released yesterday.
