### ISSUE TITLE
I want use .pem file to connect to DDBB

### ISSUE THREAD

**Issue by sbrocos** [sqlectron/sqlectron-gui#179]
I need connect to my remote ddbb using .pem file and I can't
use Ubuntu as S.O.

**Comment by sbrocos** [comment]
Sorry... 
Active switch ssl and I CAN CONNECT TO REMOTE DDBB WITH .PEM FILE

**Comment by maxcnunes** [comment]
Do you need use the .pem file to connect into a server through SSH Tunnel? I guess including the .pem file as **Private Key** should work. Does that not work?
What is the DB type your are trying to connect?
