### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ghedwards** [sqlectron/sqlectron-gui#180]
Performance issues / comments
- Query results view with large column set seems to perform badly, I've experimented with react-virtualized and slickgrid. Slickgrid seems to perform the best.
- Tables tree causes query editor to be quite laggy when there are a lot of tables.

**Comment by BornaP** [comment]
Thanks for the feedback @ghedwards ! We are aware of the first point you made. Regarding the second one, could you explain a bit more, how much tables do you have? Do you find it laggy because of live auto complete? Because I did not find it to be laggy on databases with around 130 tables. (without using auto complete feature).

**Comment by maxcnunes** [comment]
I have replaced the vanila HTML table with [fixed-data-table](https://github.com/facebook/fixed-data-table). I have not published yet because the build on CI is not working properly due http://stackoverflow.com/a/37559463/1050818. In the next release it should present a better performance.

**Comment by ghedwards** [comment]
fixed-data-table seems to have performance issues as well and the project seems to be abandoned and not compatible with new versions of React? Slick grid is ok, but seems too to be a bit of a dead end, I've started looking at / coding https://bvaughn.github.io/react-virtualized/ as a replacement.

**Comment by ghedwards** [comment]
1045 tables.. no further comment about the tables issue for now..

**Comment by maxcnunes** [comment]
Not sure about the performance issues with fixed-data-table. But that is really not actively maintained over the last months. But what I have looked in react-virtualized I could not find support for grid with a header rows. That is why at the end I have used fixed-data-table.
Could wait until the next release to check if the performance has improved?

**Comment by ghedwards** [comment]
100+ rows, 50+ columns.. scroll is laggy and slow. Running straight from master.

**Comment by maxcnunes** [comment]
😢  Sorry, but I have just replaced the vanilla HTML table with fixed-data-table. I'm not really in the mood right now to rewrite it again with another library. Although a PR would be gladly accepted 😄

**Comment by ghedwards** [comment]
Done, just need to clean up the code a little and make it look a bit nicer. Might have a PR in the next few hours or so.
<img width="712" alt="screen shot 2016-06-03 at 7 58 30 am" src="https://cloud.githubusercontent.com/assets/125586/15762412/feae7610-2960-11e6-8d31-86fdc6f5af5e.png">

**Comment by maxcnunes** [comment]
Closed on https://github.com/sqlectron/sqlectron-gui/commit/678f7429f6d779cabbb6dcab3eb2f31a3bf90c04
