### ISSUE TITLE
UI issue when only one record and horizontal scroll

### ISSUE THREAD

**Issue by eMerzh** [sqlectron/sqlectron-gui#190]
I've juste updated to the latest 1.9 (congrats for the release 👍 )

and i got a small ui issue when there is an horizontal scroll bar and only 1 record

All Good:
<img width="488" alt="capture d ecran 2016-06-06 a 21 37 28" src="https://cloud.githubusercontent.com/assets/177003/15835205/2c20b6aa-2c2f-11e6-8037-57319010bf24.png">

Not Good:
<img width="503" alt="capture d ecran 2016-06-06 a 21 37 41" src="https://cloud.githubusercontent.com/assets/177003/15835208/2fc500cc-2c2f-11e6-8186-bf490f54b895.png">

**Comment by maxcnunes** [comment]
What OS are you using? I saw this problem occurring in a Linux today. But that have not happened to me at anytime during the tests on Mac.

**Comment by eMerzh** [comment]
OSX 10.11.5
MacBook Pro (Retina, 15-inch, Late 2013)

hope this helps..

**Comment by BornaP** [comment]
This also happens on Ubuntu (15.04), but only when I try to resize column width.

**Comment by vundyalaavinash** [comment]
+1

**Comment by maxcnunes** [comment]
@eMerzh I could reproduce following your steps. I will try take a look on this.
