### ISSUE TITLE
Switch database after connecting?

### ISSUE THREAD

**Issue by xingped** [sqlectron/sqlectron-gui#193]
So I have a local postgresql installation and when I connect, i can see my two databases, but I can't actually switch between databases. I know I can set which database I connect to in my connection settings prior to connecting to my postgres installation, but it'd be nice to have some way to switch the active database once I'm already connected. (Unless there's already some way to do this that I haven't found yet?)

**Comment by BornaP** [comment]
You can switch databases by simple double clicking database name on the side menu. It will open new query tab which will be related to that database connection. 

Also you don't have to specify your database when connecting on database server, it's optional :)

**Comment by xingped** [comment]
Oh awesome, thanks!

**Comment by BornaP** [comment]
You're welcome. Thanks for the feedback, probably indicator we should improve UX on that.
