### ISSUE TITLE
rpm version

### ISSUE THREAD

**Issue by sombriks** [sqlectron/sqlectron-gui#197]
RPM version would be quite useful for fedora/redhat/centos/suse users.

**Comment by vikas-0** [comment]
yes, rpm version

**Comment by maxcnunes** [comment]
@sombriks @vikas-0 could you check this works for you? https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.10.0

**Comment by maxcnunes** [comment]
Closing it since I have not received any response. Please reopen it in case that does not work.

**Comment by sombriks** [comment]
Hello max sorry for delay.

i tried the rpm listed however with no luck.

i got this on my console: 

```[sombriks@sephiroth Downloads]$ sudo rpm -ivh Sqlectron-1.10.0.rpm 
erro: Dependências não satisfeitas:
	libappindicator1 é requerido por Sqlectron-1.10.0-252.x86_64
	libnotify-bin é requerido por Sqlectron-1.10.0-252.x86_64```

i am quite sure i have such dependencies:

```Instalados:
  libappindicator.x86_64 12.10.0-10.fc23   libdbusmenu.x86_64 12.10.2-9.fc23   
  libdbusmenu-gtk2.x86_64 12.10.2-9.fc23   libindicator.x86_64 12.10.1-5.fc23  

Concluído!
[sombriks@sephiroth Downloads]$ sudo dnf install libnotify
Última verificação de data de vencimento de metadados: 2:01:39 atrás em Tue Jul 12 17:15:14 2016.
Pacote libnotify-0.7.6-7.fc23.x86_64 já está instalado, ignorando.
Dependências resolvidas.
Nada para fazer.
Concluído!```

is there any kind of information that i could provide in order to figure why rpm releases doesn't work on fedora boxes?

**Comment by maxcnunes** [comment]
@sombriks no worries. That problem should be fixed in the latest version. Could you try that out?
Thanks

**Comment by sombriks** [comment]
@maxcnunes Indeed!

it's up and running, thank you so much!

![captura de tela de 2016-07-12 20-13-41](https://cloud.githubusercontent.com/assets/556695/16786705/3dc32136-486d-11e6-8813-56902404f867.png)
