### ISSUE TITLE
Add ability to rename query tabs

### ISSUE THREAD

**Issue by bbiagas** [sqlectron/sqlectron-gui#202]
Currently, the only way that I see available to rename a tab is if you choose to save a particular query to disk. I think there's a valid use case for wanting to rename tabs while you're doing some work in a session to keep yourself organized without having to create a bunch of files you might not want.

**Comment by maxcnunes** [comment]
I don't think other apps has this option. But if anyone is interested in implementing it I would gladly accept a pull request.
