### ISSUE TITLE
Passwords in sqlectron.json are stored in plain text

### ISSUE THREAD

**Issue by bbiagas** [sqlectron/sqlectron-gui#203]
Passwords for a server configuration are hidden from the user within the GUI, but are stored as plain text on disk inside the sqlectron.json file. JSON configuration is very handy, but database/ssh passwords should not be accessible in this way.

**Comment by maxcnunes** [comment]
It is duplicated https://github.com/sqlectron/sqlectron-gui/issues/168. Closing it in favor of the other issue.
I don't have much time to implement it now. I hope do this in the future. But if anyone is interested in implementing it earlier I would gladly accept a pull request 😄
