### ISSUE TITLE
One row result clipped by scroll

### ISSUE THREAD

**Issue by plandevida** [sqlectron/sqlectron-gui#204]
Hi, 

When the result has only one row, it shows clipped by scroll bars.

Regards.

![whatsapp-image-20160614](https://cloud.githubusercontent.com/assets/1167738/16560713/616b276a-41f5-11e6-889c-618603c536ae.jpeg)

**Comment by VisualBean** [comment]
Im about to create a PR to fix this

**Comment by plandevida** [comment]
Hi guys,

I uploaded a PR fixing it [https://github.com/sqlectron/sqlectron-gui/pull/205](url).

**Comment by maxcnunes** [comment]
Closing it, since this has been fixed by @plandevida on #205.
