### ISSUE TITLE
Not enough error context

### ISSUE THREAD

**Issue by krainboltgreene** [sqlectron/sqlectron-gui#209]
A bad query that results in an error will only show a single line, whereas on postico it shows the full context of the error.

**Comment by maxcnunes** [comment]
Could you give an example of that? For me the error messages are pretty helpful:

![screenshot from 2016-07-19 08-43-05](https://cloud.githubusercontent.com/assets/680356/16948990/72ba8a7a-4d8e-11e6-99bf-1e84acf7f62a.png)

**Comment by krainboltgreene** [comment]
Here's an example of where Postico gives more detail (if not much more context), but it's really relevant when you get failing stored procedures.

<img width="1431" alt="screen shot 2016-07-19 at 7 43 59 am" src="https://cloud.githubusercontent.com/assets/334809/16954155/a019844e-4d84-11e6-875a-8d5c20db9820.png">
<img width="703" alt="screen shot 2016-07-19 at 7 44 11 am" src="https://cloud.githubusercontent.com/assets/334809/16954154/a0196d6a-4d84-11e6-983d-91442148b8da.png">
