### ISSUE TITLE
demo example don't work

### ISSUE THREAD

**Issue by tsvetkovpro** [sqlectron/sqlectron-gui#212]
why demo don't wokr?

**Comment by maxcnunes** [comment]
That is weird. Opening the [link](https://sqlectron.github.io/demos/sqlectron-demo-gui-v1.0.0.gif) directly works. I could not find the reason that is occurring there. Well, is time to upgrade the demo gif. I will wait for that to fix the preview.

**Comment by krolow** [comment]
It has exceed the size, perhaps if we resize the gif github will allow again

**Comment by krolow** [comment]
Fixed a4440034242164cd433168ac5c2821ac7a41eda1
