### ISSUE TITLE
"Select Rows" menu item could automatically give meaningful names to tabs

### ISSUE THREAD

**Issue by claudio-silva** [sqlectron/sqlectron-gui#214]
MySQLWorkbench, for instance, names the tabs with the table name being referenced on the query, so if we right click the Users table, for instance, and pick "Select Rows", a tab will open with the query and it will be named "Users".
That is very useful to distinguish between tabs, otherwise you'll have to open each one in turn to remember which table was being queried (as "SQLFile 1", "SQLFile 2", etc, is not useful at all for this use case).

**Comment by krolow** [comment]
what happens in MySQLWorkbench when you select more than one table at once?

**Comment by BornaP** [comment]
I suggest naming tabs after database connection, instead of selected tables as several queries on different tables may be chosen in the same SQL tab.
If more then one tab is opened on the same database connection, it could be suffixed with integer. Ex. 'information_schema', 'information_schema 2' and so on.
This would give user quite useful info to distinguish tabs.

**Comment by claudio-silva** [comment]
@krolow In MySQLWorkbench you can't use the "Select Rows" menu item when right clicking on multiple tables, it's only available for a single table.
MySQLWorkbench still names other query tabs as "Query 1", "Query 2", etc.
It only gives non-generic names to tabs when they are loaded from a file, or when they are opened from the "Select Rows" command on a single table.
Still, most of the time, this is quite enough. Complex queries get a "Query X" generic title, but tabs opened for viewing a single table get the table name.
If you later change the query to refer to another table, or to join other tables, the tab still retains its name.
It's just a simple functionality to help disambiguate tabs, it's nothing fancy, but it's still quite useful, and, IMHO, it would be better than the current way sqlectron-gui does it.

**Comment by BornaP** [comment]
Nice 👍
