### ISSUE TITLE
There's no mention of the wiki in the readme

### ISSUE THREAD

**Issue by waltton** [sqlectron/sqlectron-gui#216]
Took me a time to find the shortcuts in the wiki, would be nice to have mentioned in the readme that the wiki has some documentation.

**Comment by maxcnunes** [comment]
You may have not noticed but there is link to the shortcut list in the app.
![screen shot 2016-08-16 at 7 57 54 pm](https://cloud.githubusercontent.com/assets/680356/17718776/220529c2-63ec-11e6-8eba-f92e9442043b.png)

Anyway, you are right. I have included that in the readme as well. Thanks.
