### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by alangregory** [sqlectron/sqlectron-gui#217]
Client returns "No results found"  even if i know there are results.

**Database**: postgresql
**Sqlectron version**: 1.12.0
**O.S.**: Elementary OS Freya 0.3.2

**Comment by maxcnunes** [comment]
That is weird. Lets try to understand what is going on: 

* Are you executing a select statement? 
* Are you executing a single statement or multiple statements?
* Does executing it on another sql client gives a different result?

If you could provide the sql statement you are using or a modified version of that would help.

**Comment by alangregory** [comment]
Yes, select statement -> `SELECT * FROM "connections" LIMIT 50;`
Query via cli or using Navicat gives a  diferent result

**Comment by alangregory** [comment]
Tested now, it works with sqlectron-term.

**Comment by maxcnunes** [comment]
Sorry, I really don't know what is going on. It is working for me on Ubuntu 16.04; Sqlectron 1.12; Postgres;

Here is a similar query:
![screenshot from 2016-08-15 11-57-33](https://cloud.githubusercontent.com/assets/680356/17668427/85d3a96e-62df-11e6-99b0-4dcb8bec10e4.png)

**Comment by alangregory** [comment]
Found that mysql works fine , i think potsgresql may be running an outdated version, i'll try it again after update.

**Comment by derek9gag** [comment]
I am getting the same issues - no results when I am 100% sure there are.

My set up is similar : sqlelecton, 1.15.0-305; Ubuntu 16 - the backend is Amazon Redshift.

An example of query I try to run : `select * from stats limit 1;` The table is definitely non-empty, I can do the same query (as same user) via psql cli.

How do I get more information to troubleshoot?

**Comment by maxcnunes** [comment]
That is really weird. I don't see how that could happen. Nowadays there is no easy way to debug the app in the release version. You probably would need to run the app from the source and include some logs manually to see what is going on. If you are interested on doing that and need help on how to do that, just let me know.
