### ISSUE TITLE
Execute only selected parts of the SQL file

### ISSUE THREAD

**Issue by ignacio-ifm** [sqlectron/sqlectron-gui#218]
DB: Postgres
Version: 1.12.0

Other SQL clients allow the user to execute only the selected part of the SQL in the editor. It is a useful feature because it allows the user to have all commands related to the same task in a single file.

**Comment by maxcnunes** [comment]
Are you sure it is not working? This feature is already included in the app.

**Comment by ignacio-ifm** [comment]
I see now that this is already possible via the ui, sorry for the wrong report.
