### ISSUE TITLE
Keep connection open for new transactions

### ISSUE THREAD

**Issue by ignacio-ifm** [sqlectron/sqlectron-gui#219]
DB: Postgres
Version: 1.12.0

PGAdmin (and other SQL clients) allow the user to start a transaction with

`BEGIN;`

then execute some statements (by selecting parts of the text) and end with a:

`COMMIT;`

or

`ROLLBACK;`

when changes should be discarded.

**Comment by maxcnunes** [comment]
I guess it should work, since the tab always uses the same connection. But since I have never tested it out, I will need check it better.

**Comment by ignacio-ifm** [comment]
I checked it further, it works. I just was not used to the fact that tabs in the same window share the connection so to actually check it is better to have other window (with a new connection).
