### ISSUE TITLE
Is there a way to show the DDL for a table?

### ISSUE THREAD

**Issue by dbkaplun** [sqlectron/sqlectron-gui#227]
Would like to see the SQL used to create a table (columns, indices, etc) in a DB much like DataGrip.

**Comment by maxcnunes** [comment]
Right click over a table in the sidebar shows a context menu with an option `Create Statement`. Is that what you need?

**Comment by dbkaplun** [comment]
`Create Statement` is close to what I'm looking for, but it does not include indices and other data relating to the table. Also, the text "Create Statement" is not particularly obvious and a little scary.

**Comment by maxcnunes** [comment]
I guess that name was copied from MySQL Workbench. Any better suggestion?
By [this definition of DDL](https://en.wikipedia.org/wiki/Data_definition_language) for `Create Table Statement` looks like we have got all the requirements:

> CREATE TABLE statement
> A commonly used CREATE command is the CREATE TABLE command. The typical usage is:
> ```sql
> CREATE TABLE [table name] ( [column definitions] ) [table parameters]
> ```
> The column definitions are:
> 
> * A comma-separated list consisting of any of the following
> * Column definition: [column name] [data type] {NULL | NOT NULL} {column options}
> * Primary key definition: PRIMARY KEY ( [comma separated column list] )
> * Constraints: {CONSTRAINT} [constraint definition]
> * RDBMS specific functionality

For example, this is what I got from one of my tables on MySQL:
```sql
CREATE TABLE `client` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `realm_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `secret` char(32) NOT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_client_user1_idx` (`user_id`),
  KEY `fk_client_realm1_idx` (`realm_id`),
  CONSTRAINT `fk_client_realm1` FOREIGN KEY (`realm_id`) REFERENCES `realm` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_user1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8
```

**Comment by eMerzh** [comment]
might not be the case for all database, 
not sure PG extract all indexes, ...

@dbkaplun what is your DB exactly?

**Comment by dbkaplun** [comment]
```
SELECT version();
PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
```

**Comment by jmealo** [comment]
**For views, materialized views and functions:**
https://github.com/postgres/postgres/blob/55c3391d1e6a201b5b891781d21fe682a8c64fe6/src/bin/psql/command.c#L3338

**For tables:**
http://stackoverflow.com/a/16154183/1337301

**Note about ``serial`` and ``bigserial``:**
```sql
id integer DEFAULT nextval('vendors_id_seq'::regclass) NOT NULL
-- could possibly be replaced with
id serial NOT NULL
```
(If a column has a default value that with a ``nextval`` incrementing a sequence whose name matches the ``tablename_columname_seq`` pattern it would be nice to change the datatype to ``serial`` or ``bigserial``as needed)

I'd recommend seeing what queries pgadmin, etc are issuing to generate DDL.

If all else fails one  could poke around see how ``CASCADE`` does dependency tracking to see if we can sniff out anything else we need.

**Comment by maxcnunes** [comment]
Thanks @jmealo for the details. Anyone interested on improving that please do. Here is the code we use nowadays to build the "Create Script": https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/postgresql.js#L273

**Comment by MasterOdin** [comment]
This feature is generally supported, though there are still parts of the create DDL for postgres that are not generated properly (like the serial / auto increment). These are being tracked in https://github.com/sqlectron/sqlectron-core.
