### ISSUE TITLE
Misalignemnts in results header / data

### ISSUE THREAD

**Issue by eMerzh** [sqlectron/sqlectron-gui#233]
i was doing a request with more columns than what fit in the screen and sqlectron gives me a weird alignment of the column names with the data ...

<img width="902" alt="capture d ecran 2016-09-18 a 23 29 48" src="https://cloud.githubusercontent.com/assets/177003/18619255/1a63bb7c-7df8-11e6-8f41-62107c823b7b.png">

**Comment by maxcnunes** [comment]
I have realized it before too. It occurs sometimes :cry:
