### ISSUE TITLE
Inline edits

### ISSUE THREAD

**Issue by borisrorsvort** [sqlectron/sqlectron-gui#246]
I believe inline edits from the table or preview is a must for a db client. Is this something that is on the roadmap?

**Comment by maxcnunes** [comment]
The main idea for this project is to be a simple DB client. Although many new features I didn't initially think on adding to the project have being add gradually. I won't implement it by myself, because I don't really miss this kind of feature. But a PR is welcome 😄

**Comment by borisrorsvort** [comment]
Okido, thanks for clarifying :+1:

**Comment by inspire22** [comment]
Yeah I'd call it a must as well :(  If I only had more time to dive into it myself, really love the overall design/philosophy of this project
