### ISSUE TITLE
Configurable timeout

### ISSUE THREAD

**Issue by geekgonecrazy** [sqlectron/sqlectron-gui#247]
Database type: mssql

I've got a logging table I have to query from time to time that can take up to 5 minutes or so to respond.   With sqlectron it times out before I get results.

![image](https://cloud.githubusercontent.com/assets/51996/19079477/5d2b9fb0-8a19-11e6-9520-dc6c1a437a5b.png)

I was unable to find any place to configure this, is this something that could be added?

**Comment by eMerzh** [comment]
hum... I'm not aware of timeout ... but if there are some,  i really don't see why...

**Comment by geekgonecrazy** [comment]
@eMerzh yeah 15 seconds is really, really short in my experience.  Maybe others are lucky to work with small data sets :smile:

**Comment by eMerzh** [comment]
seems to be related to mssql,

in pgsql and mysql:
```sql
SELECT SLEEP(20);
```
doesn't seems to trigger the issue.

**Comment by eMerzh** [comment]
ok, the sqlectron-core's mssql driver has a default timeout of 15000ms
> requestTimeout - Request timeout in ms (default: 15000).

**Comment by maxcnunes** [comment]
The only problem I see nowadays is that is not possible to cancel a on going query. So with a infinity timeout you could get stuck in a really long query. But since we have plans to add support at some point to cancel the query #221. I guess changing the timeout to infinity already is not a problem.

**Comment by geekgonecrazy** [comment]
@eMerzh once again you rule 👍  i'll give it a go and see what happens.

**Comment by eMerzh** [comment]
i think i can close this then....
