### ISSUE TITLE
Put the active database at the top, possibly highlited

### ISSUE THREAD

**Issue by krainboltgreene** [sqlectron/sqlectron-gui#251]
Because SQLectron shows all databases it's often a bit confusing what database I'm actually talking _too_. This might be because I'm only usually talking to one at a time, but it's still a UI problem.

Here's an example: http://www.giphy.com/gifs/3oz8xPleNGG6EgzbH2

**Comment by krainboltgreene** [comment]
(By the way, I would love to work on this if approved)

**Comment by BornaP** [comment]
👍  PR is welcome on this.

**Comment by maxcnunes** [comment]
I have add the preload filter support on v1.19.0 and background database in some previous version:

* transparent: not connected DBs
* blue: connected DBs
* yellow: current connected DB which the current query tab is related with

With those features. Does it issue still something we want to do? Or can I close it?

**Comment by krainboltgreene** [comment]
I feel good about it.
