### ISSUE TITLE
Enable connecting to database without password

### ISSUE THREAD

**Issue by MarioBlazek** [sqlectron/sqlectron-gui#253]
I would be nice if there could be a way to connect to database that have not password set.

I think @BornaP can help :).

Thanks.

**Comment by BornaP** [comment]
I believe this was enabled in earlier versions. @MarioBlazek tried connecting to MySQL with v1.15 without entering the password. Connection testing went fine, but clicking Connect button failed, which is weird.

**Comment by maxcnunes** [comment]
I have just tested on v1.15 a connection without password and it worked the test and connect buttons.
![screen shot 2016-10-12 at 09 30 47](https://cloud.githubusercontent.com/assets/680356/19310079/b6210696-905e-11e6-88b5-392bcee5e7dc.png)
![screen shot 2016-10-12 at 09 30 56](https://cloud.githubusercontent.com/assets/680356/19310080/b67df41e-905e-11e6-8187-4e2c6b1d69c4.png)
If either buttons were not working I would say was a configuration problem. But if it works the test but does not work the connect I have no idea what could be the problem. Does it show an error message?
