### ISSUE TITLE
Showing bit value on mysql table

### ISSUE THREAD

**Issue by ahrherrera** [sqlectron/sqlectron-gui#260]
my table contains a BIT value, the database is on MySQL, at querying its does not show as 1 or 0.

![screen](https://cloud.githubusercontent.com/assets/15525993/19494562/f77df922-953c-11e6-88d7-14333dd5c678.png)

**Comment by maxcnunes** [comment]
Probably it is showing the raw structure type. I guess the data field contains the bit value.

**Comment by enVolt** [comment]
Any one is looking into this?

**Comment by maxcnunes** [comment]
@enVolt I guess nobody is looking into that. Would you like to fix that? I'm almost sure the place to fix that is here https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/utils/convert.js#L19.
