### ISSUE TITLE
Can't connect to Redshift

### ISSUE THREAD

**Issue by donspaulding** [sqlectron/sqlectron-gui#271]
Hi there,

I'm loving using Sqlectron for connecting to my Postgres databases, but it's still not working great for Redshift databases yet.  In previous versions, it would connect but not be able to get results, and I think this is related to the schema work that's talked about in https://github.com/sqlectron/sqlectron-gui/issues/153  However, in 1.17.0, there seems to be a regression where it can't even connect anymore.  Here's the error:

```
Connection Error
unrecognized configuration parameter "application_name"
```

Based on this error cropping up in other projects, I think it's related to newer pg libraries specifying a connection parameter that 8.4 didn't support.   Is there anything I can do to help troubleshoot this error further?  I'm happy to run from a source checkout if you can point me to a likely place the error is coming from, or just generic developer documentation.

Thanks.

**Comment by maxcnunes** [comment]
Was included the **application_name** in the postgres connection. So it is easier to find out a process running on PG from sqlectron. I had not realized it was not available in previous versions. I will change the code to use that property only in the versions with support for that.

**Comment by iwozzy** [comment]
Happy to help troubleshoot as needed! Really looking forward to connecting to Redshift with Sqlectron :)

**Comment by iwozzy** [comment]
Getting this to work would be huge! Accessing Redshift right now is a pain :(

**Comment by maxcnunes** [comment]
Ok. I will try fix that this weekend.

**Comment by maxcnunes** [comment]
Fixed the problem with the **application_name**. New release available https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.18.0.

**Comment by iwozzy** [comment]
Thanks so much! It connects now. 
However I am not able to query anything. It doesn't show any tables on the left hand side, and querying doesn't return any results.
![image](https://cloud.githubusercontent.com/assets/4137844/21084509/8a42dc9a-bfb9-11e6-9f1e-c850d7b336fb.png)

**Comment by maxcnunes** [comment]
Probably your public schema is empty. And you are trying to access a db/table from a different schema. Unfortunately we do not support different schemas yet. Although there is a PR open to solve part of this problem. What you can do for now to at least be able to execute the query I guess is change the current schema inside the query http://stackoverflow.com/a/25014153/1050818.

**Comment by iwozzy** [comment]
Yes, that's right :( That would be amazing.
I've tried various combinations of what that post suggests but I can't get it to return any data. It's always no results found, although the column names are correct.
Any ideas?
![image](https://cloud.githubusercontent.com/assets/4137844/21088181/bbfddb90-bfe1-11e6-9a21-7dffd8747f07.png)

**Comment by maxcnunes** [comment]
I just realized that will not work :( Because each statement is executed separated. So the second statement will be executed with the default schema.
I will try this week to merge this PR, so is possible to define the default schema https://github.com/sqlectron/sqlectron-gui/pull/257.
