### ISSUE TITLE
Tabs are loosing state when switching between them

### ISSUE THREAD

**Issue by marvinrichter** [sqlectron/sqlectron-gui#274]
Currently Tabs are loosing state like scroll position in result, size of query frame and size of column width when switching between them.

This is quite painful when you have to switch between them very often.

**Comment by s-kem** [comment]
I'm taking a stab at fixing this one right now.

It appears that the `Tab` components in use is causing each `query` component to be entirely unmounted on tab switch, so when you switch back it's re-mounting from scratch and building a default state, which is a scroll position at 0 and a window height at 200.

I initially thought that the simple fix would be to add the `forceRenderTabPanel ` flag to the `Tabs` component (outlined here: https://github.com/reactjs/react-tabs#forcerendertabpanel-boolean ) but that caused the `UPDATE_QUERY` action to be dispatched a bit wildly. I went down a rabbit hole of trying to make components do nothing if they weren't rendered as part of the selected tab, but there's a lot of code reliant on the notion that only one `query` is actually rendered at a time.

So I worked around it by persisting the window height by storing it in the parent `query-browser` component's state and passing it (and a callback to update) down to the child `query`

I don't really like this solution, though. :\

I'm down a rabbit hole right now of trying to persist the scroll position but throwing an `onScroll` callback on the `AceEditor` component inside `query` is never getting called, so I'm not sure it's possible to go down this route and save scroll position.
