### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by bkanuka** [sqlectron/sqlectron-gui#276]
I have a laptop with a high resolution display. For GUI programs to be usable, they need to be scaled to about 150% or greater. I would love an option to zoom in or scale the interface (maybe there's a way of reading this from the GUI?).

In the meantime, there may be a way to scale with a custom CSS.

**Comment by maxcnunes** [comment]
Nowadays is  only possible to increase the size of the fonts inside the query box. Any other kind of zoom is not available yet. But looking into the electron API seems it is simple to achieve https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframe.
I can't work on that. But I would glad help if you are interested in do a PR for that.

**Comment by eMerzh** [comment]
wierd ... what kind of HiDPi is it ? 
here on my retina i don't experience this kind of issue O_o

**Comment by bkanuka** [comment]
I'm using Ubuntu.

**Comment by eMerzh** [comment]
mmh ok, but what is your resolution, pixel density ?

mmh maybe it's a linux related issue.. did not try on linux

**Comment by bkanuka** [comment]
My display is 2560x1440 on a 14in laptop. Not crazy, but I'm sure others have higher DPI screens. I use Unity and scale the screen to 1.25. 

Screenshots aren't the best tool for showing issues regarding DPI, but compare the size of the text in this bug report, which by many measures would be considered small (smaller than my parents could possibly read!!) to the text in Sqlectron. The "Search" box for example is small enough to be unusable.

I imagine the fix to this would be the same as approach that browsers like Firefox and Chrome take: to scale everything up to account for HiDPI.

![image](https://cloud.githubusercontent.com/assets/2676579/21816282/96ab7f60-d72d-11e6-865d-bfdd9a713126.png)

**Comment by maxcnunes** [comment]
To use a different zoom factor. Include this configuration on your `~/.sqlectron.json`:
```json
"zoomFactor": 2,
```
*PS:* Still have to wait a new release to use this setting.

**Comment by bkanuka** [comment]
Thank you! I can confirm that this is fixed.
