### ISSUE TITLE
Change keybinding for window reload (⌘R) or change window reload behavior

### ISSUE THREAD

**Issue by blakek** [sqlectron/sqlectron-gui#278]
Note: this is not a bug, and I would be happy to make a PR, but I wanted to see if anyone else had the same issue first.  This is more for an open discussion.

I came to Sqlectron from using a handful of DB clients together for different needs.  Some of those clients I used (Sequel Pro comes to mind) use ⌘R as the keybinding to run a query.  With this muscle-memory, I am constantly hitting the combination that maps to refresh the window.  This results in me watching the (very good) opening animation, seeing a disconnected session, and losing whatever query and past results I had open at the time.

I am proposing a couple changes:

  * changing the window reload keybinding to something other than ⌘R
  * have ⌘R do the same thing as ⌘⏎ (command-return)
  * change the window reload behavior to stop the "Server configuration not found" error (unless this is intended; in which case a different error message would be preferred)

Thanks in advance everyone!

**Comment by maxcnunes** [comment]
I guess we could just remove the short key for the window reload. That is more used in development environment at least. I'm ok using that for run the query as well. A PR for that would be awesome :)

**Comment by eMerzh** [comment]
hey i'm also often annoyed by this, 
and as in dev we have the save-reload mechanism, i'm in favor in replacing the ⌘R behavior
