### ISSUE TITLE
[GUI] Password fiels to short. Can't login to heroku Postgress

### ISSUE THREAD

**Issue by Ttommeke** [sqlectron/sqlectron-gui#280]
When i try to login with the Heroku credentials in the Electron GUI, i get an "password authentication failed for user" - Error.

I fixed this by editing the password in the .sqlelectron.json file. I noticed there that only a portion of the password was saved. I guess this is because the password field is limited in characters?

Length of my password 64 characters. only 55 were saved.

**Comment by krolow** [comment]
https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/components/server-modal-form.jsx#L324

@maxcnunes do you see any problem if we increase it to 254/255?

**Comment by maxcnunes** [comment]
But the problem is also here https://github.com/sqlectron/sqlectron-core/blob/master/src/validators/server.js#L63.

Would need to change those two places. Maybe we should increase the size for the other fields as well. Or maybe even remove the limit.

**Comment by eMerzh** [comment]
yeah i'm in favor of removing them if they don't add any value.

btw, i guess you'll see it , but don't forget also the server password that is limited to 55 char as well
https://github.com/sqlectron/sqlectron-core/blob/master/src/validators/server.js#L114

**Comment by krolow** [comment]
@Ttommeke would you like to give a try in fix it?

**Comment by Ttommeke** [comment]
Sorry! Guess i'm to late! :/

**Comment by krolow** [comment]
😂 @maxcnunes was quickly in that one, maybe next time 👍
