### ISSUE TITLE
prevent crash when doing big query

### ISSUE THREAD

**Issue by eMerzh** [sqlectron/sqlectron-gui#283]
hi all, 
i tried to launch a select on a table with 300k rows, 
and it seems that sqlelectron doesn't really like that...
it hang ...

maybe we can find something to limit the max number of rows or stmth ?

**Comment by maxcnunes** [comment]
Looks like it is related to https://github.com/sqlectron/sqlectron-gui/issues/129

**Comment by eMerzh** [comment]
Arg ... Sorry for the duplicate
