### ISSUE TITLE
MSSQL not showing table list in sidebar.  Always says "Loading list of tables..."

### ISSUE THREAD

**Issue by blakek** [sqlectron/sqlectron-gui#286]
I am having an issue only on MSSQL servers, and I only noticed this issue after moving from v1.18.0 to v1.19.0.

The sidebar list of tables never loads.  The "Loading list of tables..." text is flickering while it seems to try to connect to the server.  There are no errors in the developer console.  Running `select table_name from information_schema.tables` works as expected, and querying the tables works successfully.

There are approximately 500 total tables on the DB server listed.  I've tried selecting a default database, running with no default database installed, and adding filters in the `~/.sqlectron.json` file.

Example:
![demo](https://cloud.githubusercontent.com/assets/4932702/22040365/36d5f8a4-dcc8-11e6-8726-511ab43465f1.gif)

**Comment by maxcnunes** [comment]
I have tested it and is working in my case. In your case although is not showing any error message I believe the load tables is failing. I will add an option to enable debug which will forward all the logs to file. With that we can understand why that is failing.

**Comment by augustowebd** [comment]
I have the same problem.

**Comment by maxcnunes** [comment]
@blakek or @augustowebd could you download the laster version and send me the log file? https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/logging.md

**IMPORTANT:** Replace any secret info may have in the logs (e.g. password).

**Comment by erikvido** [comment]
I looked into the code of sqlectron-core/lib/db/clients/sqlserver.js where the listTables-function for SQLServer is defined. My guess is, that this the query won't work when the DB you connect to has case-sensitive collation set and the table and column names don't match casewise. For example in my db the table is called 'INFORMATION_SCHEMA.TABLES' and not 'information_schema.tables' and my collation unfortunately is case-sensitive.

**Comment by BornaP** [comment]
@erikvido Thanks for a feedback. I strongly encourage you to make a fix, run the test and make PR on sqlectron-core repo if it fixes a problem.

**Comment by peisenmann** [comment]
I believe I'm seeing the same thing as @erikvido 
```
13:59:30.623Z ERROR sqlectron-gui: (app=sqlectron-gui, namespace=renderer:redux)
    Error { name: 'RequestError',
      message: 'Invalid object name \'information_schema.schemata\'.',
      code: 'EREQUEST',
      number: 208,
      lineNumber: 2,
      state: 1,
      class: 16,
      procName: '',
      originalError: 
       { info: 
          { class: 16,
            event: 'errorMessage',
            lineNumber: 2,
            message: 'Invalid object name \'information_schema.schemata\'.',
            name: 'ERROR',
            number: 208,
            procName: '',
            state: 1 } },
      precedingErrors: [] }
```

**Comment by StephanVolkmann** [comment]
Why this issue is closed? It is still a problem - I downloaded the current version of Sqlectron and have the same problem now... The "information_schema.tables", "information_schema.views" etc. all have to be upper case so case-sensitive databases are able to handel the queries!
