### ISSUE TITLE
Sqlectron takes over the Ctrl-R shortcut for the whole system

### ISSUE THREAD

**Issue by ignacio-ifm** [sqlectron/sqlectron-gui#287]
System: Ubuntu 14.04

When sqlectron is open, Ctrl-R does not work. This is specially annoying in the terminal, where bash by default has Ctrl-R assigned to reverse-search.

The problem goes away as soon as sqlectron is closed.

**Comment by brunolm** [comment]
I could also replicate the issue on Ubuntu 16.04.

It takes over Ctrl-R, the history lookup in the terminal doesn't work, browser (tested on Chrome/Firefox) refresh doesn't work...

**Comment by krolow** [comment]
yep it's happening to me as well, I going to give a look 👍

**Comment by krolow** [comment]
I made a fix, pr is open 👍
