### ISSUE TITLE
SQLite Connection Error Argument 0 must be a string

### ISSUE THREAD

**Issue by rsantos** [sqlectron/sqlectron-gui#290]
When I try connect in database SQLite3, it show the message "Connection Error
Argument 0 must be a string".

![screen shot 2017-01-23 at 19 03 14](https://cloud.githubusercontent.com/assets/138305/22222604/a87bbd10-e19e-11e6-89d1-49a12dbad701.png)

**Comment by maxcnunes** [comment]
You need to pass a database. If you want to use a in memory database is required to set the database as `:memory:`. Maybe you could do that the default database.

**Comment by maxcnunes** [comment]
But most of the time you would want to use a local database. Otherwise any change would be lost. For that you just need to pass the path to your database file in the database field.

**Comment by rsantos** [comment]
thanks @maxcnunes, I understood now. It worked, thanks again.
