### ISSUE TITLE
[Bug/Got work around]SSH Tunnel cannot enable Passphrase?

### ISSUE THREAD

**Issue by eqxDev** [sqlectron/sqlectron-gui#291]
Using SSH Tunnel will not allow me to click the switch to enable the Password box.

**Comment by eqxDev** [comment]
So I found a fix, if you save it first then edit it you can then tick passphrase.

**Comment by maxcnunes** [comment]
Sorry. I have fixed that already here https://github.com/sqlectron/sqlectron-gui/issues/282#issuecomment-273150382. I will release a new version with that fix later today.

**Comment by maxcnunes** [comment]
Fixed on 	698230f
