### ISSUE TITLE
Encoding Too Long.

### ISSUE THREAD

**Issue by eqxDev** [sqlectron/sqlectron-gui#292]
When connecting to my server getting the error: Encoding too long.

**Comment by krolow** [comment]
https://github.com/rzcoder/node-rsa/issues/23

are you using the private key?

**Comment by eqxDev** [comment]
Yes I am, with passphrase enabled. I check as well if its the same one for when I SSH in normally and it is.

**Comment by maxcnunes** [comment]
Could be this problem maybe? https://github.com/mscdex/ssh2/issues/422

**Comment by eqxDev** [comment]
@maxcnunes that fixed it but created a new issue...

I am connecting though SSH Tunnel using the same setting I use in Sequal Pro so I know it all works.

I connect - Asks for Passphrase - Connecting to database - Bottom left displays connection to database established - But stay on the menu and is unresponsive. A few moments later it crashes saying object destroyed.

**Comment by maxcnunes** [comment]
Could you please open a new issue for that and maybe include the log as well? https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/logging.md

Closing it since the original problem has been solved.

**Comment by maxcnunes** [comment]
@eqxDev I have solved the other bug you have found as well. (fixed with 8dbfac4)

Btw, I also got the `Encoding too long` when I was using a wrong passphrase.
