### ISSUE TITLE
.sqlectron.json File Not Generated On Install

### ISSUE THREAD

**Issue by djbreen7** [sqlectron/sqlectron-gui#293]
I've tried installing on both mac and windows (via parallels) platforms and I get this error both times

ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

![screen shot 2017-01-27 at 1 02 43 pm](https://cloud.githubusercontent.com/assets/13296622/22385693/f11b48ca-e490-11e6-9e5f-b54792a89e89.png)

**Comment by maxcnunes** [comment]
Probably is something I have changed lately. A workaround for that for now:
```
echo '{ "servers": [] }' > ~/.sqlectron.json
```
