### ISSUE TITLE
Cannot resize the left menu (database list) it reverts back to the original size

### ISSUE THREAD

**Issue by brunolm** [sqlectron/sqlectron-gui#296]
When I try to increase the left menu size (database list) it resizes back to the original size, it is impossible to resize it.

Windows
v1.20.1

**Comment by maxcnunes** [comment]
It is working on Mac. Anyone interested on fixing that on Windows please send a PR :)

**Comment by thureos** [comment]
Same on linux (ElementaryOS ~= Ubuntu 16.04)
