### ISSUE TITLE
[v1.20.2] CSV, JSON export improvements

### ISSUE THREAD

**Issue by dili91** [sqlectron/sqlectron-gui#301]
Hi, 
in my opinion it would be very nice to have these additional features:
1) export directly to file, instead of simply copying to the clipboard
2) when exporting in CSV, the ability to select a value separator

Thanks

**Comment by di48l069** [comment]
@dili91 Yes this feature will make my day!!

**Comment by clarenced** [comment]
I would like to contribute to this feature, how can I start ?

**Comment by maxcnunes** [comment]
@dlion Has added support for saving the result into CSV and JSON files. It still missing the option to choose the CSV separator. If anyone is interested to work on that, it could be set in the settings modal. Wouldn't be so flexible, but would already be very helpful.
