### ISSUE TITLE
disable autocompletion?

### ISSUE THREAD

**Issue by mgutz** [sqlectron/sqlectron-gui#302]
This seems like a very useful tool but autocompletion is **terribly** slow. Can it be disabled? I just want to be able execute queries with syntax highlighting.

**Comment by maxcnunes** [comment]
Hi. Is possible to disable the whole auto complete with `enabledAutoComplete` or just the live auto complete with `enabledLiveAutoComplete`. https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/configuration-file.md

**Comment by willschubert1977** [comment]
Hi there!
For some reason I can not disable the autocomplete. These settings is off in gui, and for sure, disabled in .config/Sqlectron/sqlectron.json

  "zoomFactor": 1,
  "limitQueryDefaultSelectTop": 100,
  "enabledAutoComplete": false,
  "enabledLiveAutoComplete": false,
  "enabledDarkTheme": true,
  "disabledOpenAnimation": true,
