### ISSUE TITLE
Any way to select a local SQLite Database?

### ISSUE THREAD

**Issue by phoenixweiss** [sqlectron/sqlectron-gui#303]
sqlectron-gui
1.20.2 (1.20.2.439)

OS X 10.11.6 (15G1217)

I can't find any possible way to select a local sqlite database stored as file on the local machine.
![db file](https://cloud.githubusercontent.com/assets/3630353/23453627/1ff06fba-fe7a-11e6-862a-3ade07c380fd.png)

The only settings possible to define are: Name, Dtabase Type and Database/Keyspace field
![settings window](https://cloud.githubusercontent.com/assets/3630353/23453677/53bcd680-fe7a-11e6-9380-cd64d2db4f8f.png)

Maybe it is not an issue in general but a lack of UI logic to handle such common user task.

**Comment by maxcnunes** [comment]
Since in SQLite the database is the file itself. You have to set the file
path in "Database" field.
But I agree the UI could be improved. Is the second time I see this
confusion.

**Comment by phoenixweiss** [comment]
Maybe just a button with a file select dialog could solve the confusion?
