### ISSUE TITLE
Problem with screen resolution

### ISSUE THREAD

**Issue by aneira92** [sqlectron/sqlectron-gui#304]
On screens of 1920x1080 it looks very small

I use version 1.20.2 on windows 10

**Comment by eMerzh** [comment]
hi, thanks for your feeback
could you try https://github.com/sqlectron/sqlectron-gui/issues/276#issuecomment-272648331 ?

**Comment by aneira92** [comment]
@eMerzh Perfect Thanks, zoomFactor": 1.3 is  perfect for me
