### ISSUE TITLE
Active tab closing instead of selected

### ISSUE THREAD

**Issue by Little-Elephant** [sqlectron/sqlectron-gui#305]
Steps to reproduce:
1) Connected to DB (MySQL, if it matter)
2) 4 tabs opened. 
3) Second tab is active.
4) Press close sign on fourth tab

Result: Second tab closed
Expected result: Fourth tab closed

**Comment by dmitrika** [comment]
Cannot reproduce it on mac. Which OS do you use?

**Comment by Little-Elephant** [comment]
ubuntu 16.10. But now i cannot reproduce it too

**Comment by maxcnunes** [comment]
Closing it since you cannot reproduce it anymore. Also, there is an [issue](https://github.com/sqlectron/sqlectron-gui/issues/311) related with the fourth tab that has just been fixed. Maybe it was related to this one.
