### ISSUE TITLE
Sidebar keeps resetting its width

### ISSUE THREAD

**Issue by pyrexed** [sqlectron/sqlectron-gui#308]
When using the double ended arrow to resize the sidebar width, it keeps restoring its width to the original size.
SQLEctron version: 1.20.2
DB version: postgresql-9.5
![sqlectron-bug](https://cloud.githubusercontent.com/assets/23460576/24239325/3316c632-0fb6-11e7-9d73-e507d1abe98d.gif)

**Comment by maxcnunes** [comment]
What is the OS you are using?

**Comment by pyrexed** [comment]
Yeah sorry, forgot to mention: Windows 7.
Also noting, used the dev-tools modified the style:"width" to an arbitrary number and it stayed that way. I believe its something to do with the react-resizeable-handle.

**Comment by jleclanche** [comment]
Dupe of #296

**Comment by BornaP** [comment]
Duplicate of #296
