### ISSUE TITLE
executingQueries[queryId].execute is not a function

### ISSUE THREAD

**Issue by lookapanda** [sqlectron/sqlectron-gui#313]
`executingQueries[queryId].execute is not a function`
I get this error when using a Cassandra database.

**Comment by maxcnunes** [comment]
Query does not have support for [`query().execute()`](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/actions/queries.js#L177). It should use `executeQuery` instead. I will fix it once I have a free time.
