### ISSUE TITLE
"Cannot read property 'name' of undefined" when i try to connect a psql

### ISSUE THREAD

**Issue by Kakoum** [sqlectron/sqlectron-gui#314]
Hello guys,

Your project is awesome, i like it :)
But i have a problem ! My connection with MySQL work good, but when i try connection on POSTGRE on the same server, i have a error "Cannot read property 'name' of undefined".
Here a screenshot of my configuration 
![sqlectron](https://cloud.githubusercontent.com/assets/13518319/25614536/9d377ba6-2f32-11e7-8a9e-bb306084e61c.JPG)
I think my configuration is good because on the same server, my connection on MySQL with Sqlectron work good.
Maybe you have idea ? I searched on issues, but i dont see this problem.

(sorry for my basic english).

Thanks ! :)

**Comment by eMerzh** [comment]
Hi, 

thanks for the report, 
could you try to give us some logging info, 
https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/logging.md

Thanks
