### ISSUE TITLE
Collapse sidebar option

### ISSUE THREAD

**Issue by gooddadmike** [sqlectron/sqlectron-gui#317]
I would like an option to collapse the sidebar. 
It could probably be done one of two ways.
One way would be to collapse down to just a little autohide `<` indicatore.
Another way would be to show a small icon for the db type and a truncated name (or maybe it shows name only on hover).

**Comment by mcastre** [comment]
hello @gooddadmike! I'd love to help you out on this issue! Are you referring to the sidebar that displays when you make a connection to a db?

**Comment by gooddadmike** [comment]
Yeah. Hiding the connection tab that takes up the left side of the screen. IIRC

**Comment by gooddadmike** [comment]
Yes. Once the connection is made you have the sidebar that has search and database tables/schema options. I would like to be able to hide that when I'm working on the same sql file for a long time, for example.

**Comment by haivp3010** [comment]
I notice this issue hasn't been active for 15 days, so I just created a PR for it. Please take some time to review it. I don't know if the implementation of the sidebar is beautiful enough or not :grimacing:
