### ISSUE TITLE
SSH Tunnel -> Private Key -> (file browse button) does not work on Ubuntu/Mint

### ISSUE THREAD

**Issue by clayzermk1** [sqlectron/sqlectron-gui#320]
### Environment
Sqlectron 1.20.2
Linux Mint 18.1 Serena (Ubuntu 16.04) running Cinnamon 3.2.7
PostgreSQL 9.6.3

### What happened?
I was setting up a new database connection and the SSH Tunnel -> Private Key -> file browse button depresses but a file picker never appears.

### What did you expect to happen?
I expected a file picker to appear when I click the button.

### Work-around
I was able to edit the `~/.sqlectron.json` file and add the private key path. Reloading Sqlectron brought in the changes and the connection worked.

**Comment by maxcnunes** [comment]
For me on Mac it is working. Please could someone with Ubuntu check it out?

**Comment by damien-biasotto** [comment]
Just tried it on ubuntu 17.04 and sqlelectron 1.20.2, and it's working fine 


![image](https://cloud.githubusercontent.com/assets/430633/26609645/a4eb9fca-45e5-11e7-9f41-eaa00871b031.png)

**Comment by clayzermk1** [comment]
Huh, wonder if it's a library difference between the Ubuntu versions. Good to know, thanks @damien-biasotto for checking that out.

**Comment by maxcnunes** [comment]
@clayzermk1 We just use a simple HTML file input. It should work normally in any OS. Try opening the devtools to see if there is some error in the console.

**Comment by clayzermk1** [comment]
FYI, I won't be swinging back around to this any time soon (that computer is in another country) so I'll close it for now. Thanks all for taking a look.
