### ISSUE TITLE
Error: Object has been destroyed when closing new window

### ISSUE THREAD

**Issue by jleclanche** [sqlectron/sqlectron-gui#328]
If I open sqlectron, then in the window that was just opened I go to `File -> New window`; then close that new window, I get the following message:

![image](https://user-images.githubusercontent.com/235410/27257457-07c8cf66-53e0-11e7-9b4c-7ae4adb0f7bd.png)

**Comment by maxcnunes** [comment]
Does that happen for what DB client? Does that happen for the first window as well? Could you provide the logs for that error?

**Comment by jleclanche** [comment]
It happened the very first few times I used sqlectron, before I even added a db. However I can't get it to reproduce anymore but that might be because I upgraded to the latest version... I was one version behind before.

**Comment by maxcnunes** [comment]
So lets close it for now. Please reopen it if you can reproduce again later.
