### ISSUE TITLE
How to change app font and editor font?

### ISSUE THREAD

**Issue by sunzhenyucn** [sqlectron/sqlectron-gui#330]
the default font is ugly,i want to change it,how to do?

**Comment by sunzhenyucn** [comment]
and how to chanage language?

**Comment by maxcnunes** [comment]
Sorry, I didn't see this issue before. Nowadays it isn't possible. But shouldn't be too complicated to make it configurable. Although I'm fine with the current font so I won't spend time on this. But I could help you out guiding you on making those changes.
