### ISSUE TITLE
Ignored passphrase for private key for SSH 

### ISSUE THREAD

**Issue by mamonth** [sqlectron/sqlectron-gui#331]
If private key protected with passphrase, it impossible to provide it on server add\edit dialog. So "test connection" button retrun error "Encrypted private key detected, but no passphrase given".

When trying to connect from server list window - application asks for passprase but do not use it actually, and return same error as above.

**Comment by maxcnunes** [comment]
It used to work. I don't have much time to work on this. But if anyone needs help debugging and fixing this please let me know.

**Comment by cshwery** [comment]
yeah, I had this same issue. It prompts you to enter your passphrase, but the error says "no passphrase given"

**Comment by budik21** [comment]
I can only confirm, that the same behavior has occured at me too.

**Comment by markpanado** [comment]
Same to here...

![image](https://user-images.githubusercontent.com/3646720/29663894-dc52e786-88ff-11e7-87d0-0d8b02102052.png)

**Comment by guruarumugam** [comment]
has this been fixed? I hit the same issue today.

![image](https://user-images.githubusercontent.com/12170988/32823892-e1ad108e-ca32-11e7-9ffd-cfd7f007f4dd.png)

**Comment by guruarumugam** [comment]
A few more clicks showed that the same issue occurs when you click on the test connection button on the add connection screen.
