### ISSUE TITLE
Cannot Save If There Is No Default Port

### ISSUE THREAD

**Issue by colecmc** [sqlectron/sqlectron-gui#334]
SQLectron is an awesome product. Thanks for sharing it.

I am using Version 1.22.0 (1.22.0.459) on a Mac: version 10.11.6 (15G1004). And I cannot connect to a Microsoft SQL DB because a default port is being added.
When I remove the default port, I am able to test the connection successfully, however I'm not able to save it.

What am I doing wrong? Please help.
![screen shot 2017-07-27 at 12 04 02 pm](https://user-images.githubusercontent.com/2650825/28682656-4eefdda6-72c3-11e7-9ca9-0c4340bc5d07.png)

**Comment by maxcnunes** [comment]
That is weird. A port is required for any connection. Are we using the wrong default port for Microsoft SQL DB?

**Comment by colecmc** [comment]
Hello @maxcnunes, Yes, I think it's weird too. The connection details provided to me by our sysadmin, did not include a port number.

**Comment by colecmc** [comment]
I uninstalled, and then reinstalled v1.21.0 and it seems to be working now. I have no idea what the cause was.
