### ISSUE TITLE
CSV DateTime Export

### ISSUE THREAD

**Issue by msopko81** [sqlectron/sqlectron-gui#345]
When doing a CSV export, datetime columns do not export properly. Run this query:

```sql
SELECT CAST('2017-09-18' AS DateTime) AS FIRST,
       CAST('2017-09-18' AS DateTime) AS SECOND,
       CAST('2017-09-18' AS DateTime) AS LAST
```

CSV gets exported like:
```
FIRST,SECOND,LAST
1505692800000,1505692800000,2017-09-18T00:00:00.000Z
```

DateTime fields will only be exported properly if it is the last column. JSON works as expected:
```json
[
  {
    "FIRST": "2017-09-18T00:00:00.000Z",
    "SECOND": "2017-09-18T00:00:00.000Z",
    "LAST": "2017-09-18T00:00:00.000Z"
  }
]
```

Version: 1.20.2
DB: MSSQL

**Comment by CENTRALPAYMENT430207** [comment]
Select cast

**Comment by maxcnunes** [comment]
@msopko81 Does it still happening for you? I get this in the latest version:
```csv
FIRST,SECOND,LAST
2017-09-18 00:00:00,2017-09-18 00:00:00,2017-09-18 00:00:00
```

**Comment by msopko81** [comment]
I just upgraded to version 1.26.0 and am still having the same error. Not sure if this helps, but I am also running an older SQL Server version:

SELECT @@VERSION;

Microsoft SQL Server 2014 (SP1-GDR) (KB4019091) - 12.0.4237.0 (X64) Jul 5 2017 22:03:42 Copyright (c) Microsoft Corporation Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

I also tried this on SQLite and PostgreSQL databases and I do not get this issue.

**Comment by maxcnunes** [comment]
Hmm, I didn't notice you were using MSSQL. I have tested with PostgreSQL only. Sorry, I don't have an MSSQL to test it out.

**Comment by tengis** [comment]
i'm using MSSQL and also i tested on master branch. Looks like all looking fine on mine.

`FIRST,SECOND,LAST
2017-09-18T00:00:00.000Z,2017-09-18T00:00:00.000Z,2017-09-18T00:00:00.000Z
`

`[
  {
    "FIRST": "2017-09-18T00:00:00.000Z",
    "SECOND": "2017-09-18T00:00:00.000Z",
    "LAST": "2017-09-18T00:00:00.000Z"
  }
]`

**Comment by msopko81** [comment]
I tested with the latest release and this issue has been resolved. 

Thank you,
