### ISSUE TITLE
Suggestion for a feature

### ISSUE THREAD

**Issue by itaispector** [sqlectron/sqlectron-gui#346]
Hi, guys!

Amazing project, love at first sight :)

Is there any chance you would develop a feature that enables editing of a row directly from the row?

Thanks!

**Comment by maxcnunes** [comment]
Hi @itaispector,

We appreciate the feedback :)

That feature has been requested a few times already.
Here is the last open issue for that: https://github.com/sqlectron/sqlectron-gui/issues/297

Closing this one since it is duplicated.
