### ISSUE TITLE
Resize Sidebar

### ISSUE THREAD

**Issue by seesemichaelj** [sqlectron/sqlectron-gui#348]
It would be nice to be able to resize the sidebar via click-and-drag on the right (or inner) border. Sometimes, the schema+table names are too long and wrap to a second line mid-character (the warp behavior is as I would expect it since these names shouldn't have spaces in them) making it slightly difficult to quickly discern the name of the table.

**Comment by maxcnunes** [comment]
@seesemichaelj What version are you using? We already have that, but it stays in the top right of the sidebar. Doesn't that work for you?

**Comment by seesemichaelj** [comment]
I have version 1.25.0-471 (via `dpkg`; is there a way to see this in the app? I went to Help>About which brought the website up instead). You are right though; I do see the resize functionality and it works as I'd expect it. I guess it's not intuitive to put it at the top as most interfaces have the drag throughout the whole thing. I could be happy with the current interface although if you wanted to keep it as is.

**Comment by maxcnunes** [comment]
I tried to keep through the whole sidebar. But I couldn't get it working well. I would gladly accept a PR for that though :)
