### ISSUE TITLE
Hacktoberfest 2017 - Looking for contributions

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#349]
The [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/) has started 🎉 

> **Support open source and earn a limited edition T-shirt**
>
> **Event details**
> 
> Hacktoberfest is open to everyone in our global community!
> Pull requests can be made in any GitHub-hosted repositories/projects.
> You can sign up anytime between **October 1** and **October 31**.
> 
> **Rules**
> 
> To get a shirt, you must make four pull requests between October 1–31 in any timezone. Pull requests can be to any public repo on GitHub, not just the ones we’ve highlighted. The pull request must contains commits you made yourself. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.

Sqlectron is looking for any kind of contribution:
* Fix typos
* Improve documentation
* Small fixings
* Or even new features

If the ticket you wanna work doesn't have a **Hacktoberfest** label, just let us know. 

---

[Check out your progress in the Hacktoberfest](https://hacktoberfestchecker.herokuapp.com/)

**Comment by iamonuwa** [comment]
Am looking for contributions... Where can I help???

**Comment by eMerzh** [comment]
@iamonuwa you can start by looking at all the Hacktoberfest tag
https://github.com/sqlectron/sqlectron-gui/labels/Hacktoberfest
or looking the app searching for typo, bug, .... and improving doc?
