### ISSUE TITLE
Query result disappears when I start typing a new query

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#35]

**Comment by maxcnunes** [comment]
Fixed on https://github.com/sqlectron/sqlectron-gui/commit/c98c32b0d35cd70cd927b1d7527540ac4d3fb62b

**Comment by krolow** [comment]
@maxcnunes you can use this https://help.github.com/articles/closing-issues-via-commit-messages/ in future commits...

**Comment by maxcnunes** [comment]
awesome :+1:
