### ISSUE TITLE
back slash commands do not work for postgres

### ISSUE THREAD

**Issue by davidgross** [sqlectron/sqlectron-gui#357]
I have Sqlectron connected to a postgres db. I would like to run `\d+ <table_name>` and other back slash commands.  However I get "syntax error at or near \\" from Sqlectron.  If I use a `psql` I can use the back slash commands.

**Comment by maxcnunes** [comment]
Those back slash commands are specific for that command line tool. They are not part of the SQL. 
On Postgres you can list tables like this:
```sql
SELECT * FROM pg_catalog.pg_tables;
```

**Comment by davidgross** [comment]
Right....`\d+` is equivalent to `DESCRIBE`, not list tables.
