### ISSUE TITLE
Signed application bundle

### ISSUE THREAD

**Issue by kolis** [sqlectron/sqlectron-gui#376]
On Mac I'm getting this.
```
“Sqlectron” can’t be opened because it is from an unidentified developer.
```
I know I can bypass this, but would be nice to have a properly signed bundle.

**Comment by maxcnunes** [comment]
Sorry, to avoid that message I would need to sign to "The Apple Developer Program". But I can't afford it since it is an open source software and that Apple Program has an annual fee of 99 USD.

**Comment by BornaP** [comment]
@maxcnunes I think I've active Apple Program, so I can try and sign it. However, it's expiring pretty soon and I won't extend it most probably, so I think we will have same issue with further releases 🤔

**Comment by BornaP** [comment]
Would be nice if Apple would give option to sign open source software for free though.

**Comment by maxcnunes** [comment]
Not sure is worth the work to configure that if it is already expiring. But that is up to you 😆 
Yeah, it is very sad Apple does not provide that for OSS.

**Comment by BornaP** [comment]
I think the same, not worth a trouble :)

Shall we close it?

**Comment by kolis** [comment]
Ok, thanks for explanation
