### ISSUE TITLE
When changing a configuration of the connection the password is lost

### ISSUE THREAD

**Issue by riquena969** [sqlectron/sqlectron-gui#377]
When I change some connection data and saved the password is forgotten. When I try to connect to the database it gives access denied, when I edit the connection again and I enter the password it connects normally.

My scenario:
- OS: Linux Mint 18.2 Cinnamon 64-bit
- Sqlectron: v1.26.0
- Database: MySQL

![errorsqlectron](https://user-images.githubusercontent.com/17579826/31816507-5adc40b6-b56f-11e7-8dd8-9e0f5569f934.png)

I'm Brazilian, sorry if I miss anything in writing. I do not speak English very well.

**Comment by maxcnunes** [comment]
Thanks for reporting that. I had fixed it already but didn't have time to release a new version.
I will do that later today.
btw I'm Brazilian too. Don't be hard on yourself, your Ensligh is good :)
