### ISSUE TITLE
Background color change ?

### ISSUE THREAD

**Issue by gabino** [sqlectron/sqlectron-gui#384]
how to change the background color, as it tires the view

**Comment by maxcnunes** [comment]
Nowadays is not possible to change the background color. I mean, if you really want that, you could do that by opening the inspector mode and changing the CSS background color. Would be nice though to support different themes.

**Comment by synle** [comment]
I added a few improvements to make the dark theme more pleasant. Below is the PR.
https://github.com/sqlectron/sqlectron-gui/pull/408
