### ISSUE TITLE
Cannot read property 'crypto' of null after press ctrl+shift+r

### ISSUE THREAD

**Issue by riquena969** [sqlectron/sqlectron-gui#394]
When I press `ctrl+shift+r` to reload the application, the following message appears: **Cannot read property 'crypto' of null**.

My scenario:

+ OS: Linux Mint 18.2 Cinnamon 64-bit
+ Sqlectron: v1.27.0
And
+ OS: XUbuntu 17.10 64-bit
+ Sqlectron: v1.27.0

![image](https://user-images.githubusercontent.com/17579826/32450046-5a3945f8-c2fa-11e7-8e45-ac01b9536545.png)

**Comment by riquena969** [comment]
For you reproduce this error, connect to a database and then press `ctrl+shift+r`. If you are not connected to a database, this error will not occur.

**Comment by BornaP** [comment]
Fixed. Will be released with next version.
