### ISSUE TITLE
How to see passwords?

### ISSUE THREAD

**Issue by mohsinhijazee** [sqlectron/sqlectron-gui#398]
I am using Sqlectron 1.26 and I have many connections saved. But unfortunately, I cannot see my passwords anymore. Is there a way that I can see the password on the UI? Or any other hack to read it from the configuration files?

**Comment by synle** [comment]
Look like you can do something like this:

```
const server = ...;
const cryptoSecret = config.data.crypto.secret;
const decryptedServer = sqlectron.servers.decryptSecrects(server, cryptoSecret);
```

**Comment by synle** [comment]
I think I found a fix for this. Will push a PR when I am back.

**Comment by synle** [comment]
PR is here
https://github.com/sqlectron/sqlectron-gui/pull/416
