### ISSUE TITLE
Typo on "query informations"

### ISSUE THREAD

**Issue by mfgabriel92** [sqlectron/sqlectron-gui#399]
Hi,

I noticed two typos in [this file](https://github.com/sqlectron/sqlectron-gui/blob/5364e9aea092e9ec2d7a46629ae47c7f18d956fb/src/renderer/components/query.jsx#L315)

The word should be "information". Letter "r" is misplaced and the word has no plural.

Thank you.

**Comment by BornaP** [comment]
Fix on master. Thank you @mfgabriel92 for pointing it out :)
