### ISSUE TITLE
Ilija

### ISSUE THREAD

**Issue by IlijaZubac** [sqlectron/sqlectron-gui#417]
Sorry, but I'm new in this. I was install sqlelectron, and I have a problem which result with this message: code: ER_DBACCESS_DENIED_ERROR
errno: 1044
sqlMessage: Access denied for user ''@'localhost' to database 'information_schema'
sqlState: 42000
sql: create table nova_tabela;
name: Error
I was install V 1.28 on PC/Windows 10 and when I put test connection without users and password that is pass, but after that, when I want to execute command, I get this message! Please help me.

**Comment by maxcnunes** [comment]
So, you are able to connect to a server. But is not able to execute any command in that? Even `select` and `insert` commands or just `create table` is not working?

**Comment by IlijaZubac** [comment]
Yes, thats true! It's the same when I tray to create database,  I always get this message.

**Comment by maxcnunes** [comment]
If `select` and `insert` queries are working. But `create table` and `create database` are not. It seems a permission issue.

**Comment by IlijaZubac** [comment]
How do I solve that issue?

**Comment by maxcnunes** [comment]
This should give all the privileges available
```sql
GRANT ALL PRIVILEGES ON * . * TO 'YOUR_DB_USERNAME_HERE'@'localhost';
```
Closing it since it is not a Sqlectron issue.

**Comment by maxcnunes** [comment]
This should give all the privileges available
```sql
GRANT ALL PRIVILEGES ON * . * TO 'YOUR_DB_USERNAME_HERE'@'localhost';
```
Closing it since it is not a Sqlectron issue.
