### ISSUE TITLE
Disable Splash Screen

### ISSUE THREAD

**Issue by funnylookinhat** [sqlectron/sqlectron-gui#426]
A frequent workflow of mine is to open multiple Sqlectron windows to manage different connections more easily - but each time a new window opens I have to wait for the splash screen to load.  This seems unnecessary and just slows down connecting to a new server.  Could we add an option to disable the splash screen?

**Comment by krolow** [comment]
would you like to contribute for this improvement?

**Comment by maxcnunes** [comment]
If you want to disable the splash screen it should be possible to do it by adding `"disabledOpenAnimation": true` to your configuration file https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/configuration-file.md

**Comment by seantcanavan** [comment]
I had no idea thank you @maxcnunes

**Comment by ch3ll0v3k** [comment]
This approach works best for me with `.nvmrc` files

```bash
PREV_PWD=$PWD;
function enter_directory {
  if [[ $PWD == $PREV_PWD ]]; then
    return
  fi
  PREV_PWD=$PWD
  if [[ -e ".nvmrc" ]]; then
    A="$(cat .nvmrc)";
    B="$(node -v)";
    if [[ "$A" == "$B" ]]; then
      # echo "same version; aborting...";
    else
      # echo "use new version; done...";
      nvm use $(cat .nvmrc);
    fi
  fi
}
export PROMPT_COMMAND="enter_directory";

```
