### ISSUE TITLE
Connecting to SQLite DB over SMB gets stuck on "Loading list of tables..."

### ISSUE THREAD

**Issue by wyoung** [sqlectron/sqlectron-gui#431]
Attempting to open a SQLite DB file on macOS over an SMB share wedges the UI: "Loading list of tables..." occasionally blinks on and off in the status bar, and it just says "Loading..." in the bottom of the pane on the left.

Dragging the same file to the desktop and opening it from there works.

And please, no lectures about the risks of opening a SQLite DB over a network file system. I already know [the risks](https://www.sqlite.org/howtocorrupt.html#_filesystems_with_broken_or_missing_lock_implementations), accept them, and can cope.

**Comment by krolow** [comment]
probably is one issue from our sqlite [connector](https://github.com/sqlectron/sqlectron-databases)

I don't think is something easy to implement as it would involve another protocol to be implemented (maybe I'm wrong), maybe you can try to use some sync the samba file in your side?

I will close the issue as it is not directly related to sqlectron
