### ISSUE TITLE
[FEATURE REQUEST] MariaDB dialog plugin support

### ISSUE THREAD

**Issue by earspace** [sqlectron/sqlectron-gui#439]
Hopefully this isn't too out of scope, as sqlectron has been a delight in many other aspects I was wondering whether support for MariaDB's dialog plugin could be supported at some point in the future.

Cheers

EDIT: Just saw the blurb about the project not being maintained :(

**Comment by MasterOdin** [comment]
mariadb has been added as an option in the add server dialog and it will be available in the upcoming 1.31 release. I'm not sure if that's what you meant or not, and it's probably 2 years out of date, but better late than never!

**Comment by MasterOdin** [comment]
Resolved in #484, #488 which will be included the 1.31.0 release
