### ISSUE TITLE
it auto delete command after you click execute then click into query texteditor

### ISSUE THREAD

**Issue by acoret** [sqlectron/sqlectron-gui#440]
like this:
1:create table Test(
2:id int,
3:joke char(20)
4:)
after click execute,and click into texteditor,click the 2th line.it will auto delete the last letter.
1:create table Test(
2:id int
3:joke char(20)
4:)
if you have choose the whole line,it will delete all.
and i found it lock the tab5 that is create after add new query windows
underfine#1 | underfine#2 | underfine#3 |  underfine#4 | underfine#5 | underfine#6
it just lock the underfine#5,i can't click into it.and it actually lock the underfine#6
i have to add new tab,and clock it ,so it will turn into last tab.

**Comment by MasterOdin** [comment]
I cannot replicate this on the latest version (1.32.0). Not sure if I'm just failing to replicate, or if it's been fixed in the meantime.
