### ISSUE TITLE
Question: How to execute query with arguments?

### ISSUE THREAD

**Issue by emersonsiega** [sqlectron/sqlectron-gui#446]
Hi

Maybe this is a dumb question, but I can't find an answer anywhere...
How to run a query with arguments like `select name from person where id = :id;`

Thanks.

**Comment by barneydmedia** [comment]
I think you're confusing SQL with query builder behaviors. When you're executing the query directly (like with SQLectron), you just plugin in whatever the value is.

`select name from person where id = 1;`
`select name from person where id in (1,2,3,4)`
