### ISSUE TITLE
Previewing a table cell shows the incorrect value when the table has been updated.

### ISSUE THREAD

**Issue by YuKitsune** [sqlectron/sqlectron-gui#447]
When I execute a select query on a table, then attempt to preview one of the cells, I get the correct data.
However, if that table updates and I re-run the query without changing the query, the table will update correctly, however, the preview window still shows the data from the old query.

Eg:
Run this query
```SQL
SELECT * FROM BugReports WHERE IsOpen = 1
```

In a new tab (or somewhere in your application), run this query
```SQL
UPDATE BugReports SET IsOpen = 0 WHERE ID = 123
```

Rerun the first query, without changing it.

### Expected result
The table will update, and I can right-click any cell and see the preview of the cell's data.

### Actual result
The table will update, but right-clicking and previewing will show the cell's data from the previous query.

It seems as though the content of the cells will change position, but the event listener linked to the preview window doesn't update to the new cell values. I haven't actually looked at the code to know for sure.

Example video: https://youtu.be/VOXW49UBHoo

Love the program so far, would love to have this bug fixed as it's been causing confusion for me and my team for a week!

**Comment by marcnaweb** [comment]
Just in case: I am having a similar behavior. 
Did you find a workaround?

**Comment by EoinAviation** [comment]
Sadly no, found out shortly after posting that the project is no longer maintained 😢
