### ISSUE TITLE
sqlectron gui working as a browser

### ISSUE THREAD

**Issue by desconectad0** [sqlectron/sqlectron-gui#466]
I don't know how to reproduce this issue, but my sqlectron somehow has finished working as a browser.
![sqlectron_browser](https://user-images.githubusercontent.com/18339302/54032752-ce249980-41b2-11e9-8873-e5e864be55cd.jpeg)

**Comment by rathboma** [comment]
That's wild. It is built using web-tech, but shouldn't really let you do that. Try restarting it and post back here if you figure out how to reproduce.

**Comment by jonorozcoc** [comment]
The most obvious way to do it is with window.location from developer tools

**Comment by antonioavelar** [comment]
I think i know the problem...

Is it possible that you clicked any kind of link? Or maybe is it possible something redirected you to that page?
