### ISSUE TITLE
server probelm

### ISSUE THREAD

**Issue by bnvsrmahesh** [sqlectron/sqlectron-gui#467]
![Capture](https://user-images.githubusercontent.com/48646958/54490180-9b2c8500-48d9-11e9-95b8-2d9812969354.PNG)

**Comment by rathboma** [comment]
Hey! Could be a couple of things:
1. Check the database is running on that machine, and that port, and that it's port is accessible to the outside world (usually this means it binds itself to 0.0.0.0 in the DB config)
2. Check that you do not have a firewall rule that prevents access to that port. If on AWS you'll have to open that port in your Security Group for the machine.

hope that helps, more info on the specific DB or environment would be helpful for further debugging.

**Comment by MasterOdin** [comment]
Closed as not really enough info here to do anything.
