### ISSUE TITLE
Running a query results in the error "Cannot match against 'undefined' or 'null'."

### ISSUE THREAD

**Issue by rathboma** [sqlectron/sqlectron-gui#469]
When checking out the project fresh on Master using Node 8 and trying to run a select query on either Postgres or MySQL causes this error in the console:

`"Cannot match against 'undefined' or 'null'."`

<img width="799" alt="Screen Shot 2019-05-02 at 8 36 31 PM" src="https://user-images.githubusercontent.com/279769/57116395-7ae64780-6d1a-11e9-9d68-056747623aac.png">

**Comment by rathboma** [comment]
So I think I'm just an idiot and didn't read the docs about a config file

**Comment by MasterOdin** [comment]
Fixed in df7005281cfcd9a50eb625b9ac0010175d650cec
