### ISSUE TITLE
Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by robertgarrigos** [sqlectron/sqlectron-gui#471]
I cannot connect to a server thru ssh tunnel and and openssh key. Got this error: 
```
Connection Error
Cannot parse privateKey: Unsupported key format
```
It's the same key I'm using to connect thru ssh to my server.

I'm on an Ubuntu 18.04.2 LTS and latest sqlectron as of today. Any ideas?

Thanks.

**Comment by btekbtek** [comment]
I had this issue today, You need to use id_rsa.pem
if You don't have, use any converter.

**Comment by btekbtek** [comment]
Ok Finally I get this to work.

What I done on my Ubuntu:
1. I use 'wine puttygen.exe'
2. convert my id_rsa to id_rsa.ppk
3. this not work so I convert id_rsa.ppk to id_rsa.pem

and its connect.

**Comment by natethor** [comment]
I'm also getting this issue.  I created my key normally on OSX terminal.  I'd rather not have to do the work-around above using wine and puttygen.  Any idea if there's plan for a fix?

**Comment by MasterOdin** [comment]
I've added this to the backlog for the next version.

**Comment by armarti** [comment]
> Ok Finally I get this to work.
> 
> What I done on my Ubuntu:
> 
> 1. I use 'wine puttygen.exe'
> 2. convert my id_rsa to id_rsa.ppk
> 3. this not work so I convert id_rsa.ppk to id_rsa.pem
> 
> and its connect.

For me the command below _nearly_ worked. Perhaps it can help someone get to the complete solution quicker.

Using puttygen-0.74 on macOS (`brew install putty`):

```
puttygen ./ssh-keygen-created.private.key -O private-openssh -o ./plain-rsa.private.key
```

Though it only connects successfully using this `./plain-rsa.private.key` when the key is decrypted. And even then it only connects successfully when clicking the **Test** button while creating the connection. When I go to to actually connect to see the tables and whatnot I get the same `Cannot parse privateKey: Unsupported key format`. Same results with rsa2048, rsa4096, and ed25519 keys.

This `puttygen` makes a distinction between **openssh** and **openssh-new** formats.

```
$ puttygen --help
...
  -O    specify output type:
           ...
           private-openssh     export OpenSSH private key
           private-openssh-new export OpenSSH private key (force new format)
...
```

The "openssh" format starts with:

```
-----BEGIN RSA PRIVATE KEY-----
```

The "openssh-new" format starts with:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by mitchbregs** [comment]
Any updates here?

**Comment by yi-mei-wang** [comment]
Facing the same issue here. Is there an update?

**Comment by maxcnunes** [comment]
It got closed by mistake, we still need to update sqlectron-db-core in the app which I plan to do this weekend.
