### ISSUE TITLE
Open SQLite encrypted db.

### ISSUE THREAD

**Issue by sina9857** [sqlectron/sqlectron-gui#472]
Hello
I have encrypted sqlite3 db. i want open it in sqlelecton, but **there is no way to insert password** for opening that file.

**Comment by MasterOdin** [comment]
Closing this as supporting passwords for sqlite as supporting this isn't really possible without also possibly breaking using non-encrypted sqlite3 databases. The problem arises here that the sqlite3 driver for node includes a copy of the sqlite3 source inside of itself. While you can substitute in another sqlite3 runtime (e.g. one with encryption), it is not possible to switch between them on the fly within the app, we would have to use one runtime or the other. For the overwhelming majority of people using sqlite3, they want the default runtime that's supplied by SQLite itself.

Sorry!
