### ISSUE TITLE
Arch Linux package extension

### ISSUE THREAD

**Issue by fhdk** [sqlectron/sqlectron-gui#478]
Is the extension `.pacman` on the release page for use with Arch LInux?

If it is so, you should know the extension **.pacman** is not a recognized extension for packages targeting Arch based system.

If compressed using xz the correct extension is **.pkg.tar.xz**.

Arch Linux has changed package compression from xz to zstd and the correct package extension for this is **.pkg.tar.zst**

https://forum.manjaro.org/t/how-to-install-a-software-with-the-extension-of-pacman/118211

**Comment by MasterOdin** [comment]
This looks like it'll be solved by just upgrade electron-builder version, which will happen in the next version of sqlectron.

**Comment by MasterOdin** [comment]
After looking into this, I'm going to close this as a "won't fix". The build process for all sqlectron releases is done through the [electron-builder](https://www.electron.build/) package and any issues with the built binaries should be filed there. In this case, it looks like a deliberate decision on their part to use the `.pacman` extension over anything else. If you'd like to see that changed, I would recommend filing a bug upstream on their repository https://github.com/electron-userland/electron-builder.
