### ISSUE TITLE
Connecting to sql database on different port than 3306

### ISSUE THREAD

**Issue by bartboersma** [sqlectron/sqlectron-gui#480]
Hi,

Locally I am running multiple docker containers running a mysql database. 

Container A is running mysql database X on port 3306.
Container B is running mysql database Y on port 3307.

Im able to connect via my Java application to both applications. However, in Sqlectron I am not able to add a connection using 'Database Type': MySQL running on port 3307 (connecting to database X on port 3306 is perfectly fine). The error I get when connecting via Sqlectron to mysql database Y on port 3307 is: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

How could I solve this problem?

**Comment by MasterOdin** [comment]
It sounds like Container B is using mysql 8? Currently, you'll have to start the container with the runtime flag of `--default-authentication-plugin=mysql_native_password` to allow the underlying mysql driver that sqlectron uses to connect. This should be resolved in the next version of sqlectron.

**Comment by MasterOdin** [comment]
Resolved in #484 which will be part of upcoming 1.31.0 release.
