### ISSUE TITLE
SQLite with password

### ISSUE THREAD

**Issue by bulog** [sqlectron/sqlectron-gui#481]
It's powerful, but is it support the SQLite database with password?

Can not input pass when switch to SQLite

**Comment by MasterOdin** [comment]
Unfortunately, this is not something that can be easily supported. SQLite itself does not support passwords, requiring you to use an extension that hooks into it to handle encryption / decryption. In that regard, there are then many such extensions (sqlcipher, SEE, wxSQLite, etc.), but that then do password protection with different algorithms / schemes.

Now, I could mandate that only sqlcipher is supported, but even then getting that setup and working is a decent chunk of pain, that I would want to avoid. If someone really wants to do the leg work of figuring out how to make this work in a way that makes it easy for building and working on with collaborators, I won't stop them, but it's not something I will probably ever do, and so closing this issue, sorry.
