### ISSUE TITLE
Need to upgrade electron - Harfbuzz version is too old

### ISSUE THREAD

**Issue by bagage** [sqlectron/sqlectron-gui#482]
An [upstream bug](https://github.com/electron/electron/issues/20348) in electron prevents `sqlectron` from starting with error message:

> Pango-ERROR **: 23:18:09.341: Harfbuzz version too old (1.4.2)

It seems the only solution is to upgrade the electron version used :/.

**Comment by MasterOdin** [comment]
PR open to update the version of electron to one which should no longer have this error, and will be available in 1.32.0
