### ISSUE TITLE
sqlectron GUI connection error

### ISSUE THREAD

**Issue by shelphysingh** [sqlectron/sqlectron-gui#483]
hi 
I am working on AWS RDS. trying for hands on 
and I just install sqlectron GUI for that

but getting error

Connection Error
ER_ACCESS_DENIED_ERROR: Access denied for user"

**Comment by MasterOdin** [comment]
Are you able to connect fine using another DB client? Have you double checked that you typed in the credentials correctly?

**Comment by secdini** [comment]
I get the same error too

**Comment by benjaminW78** [comment]
then it seem's it's not sqlEctron which is the root cause of your troubles. :p

**Comment by sushaanttb** [comment]
@shelphysingh  , @secdini 
It's a known issue which is documented by AWS. Here's the Docs Link for ref(For Postgres) : https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToPostgreSQLInstance.html

Basically apart from the usual hostname, username, password, database name is also expected when connecting.

**Comment by sushaanttb** [comment]
@shelphysingh , @secdini
It's a known issue which is documented by AWS. Here's the Docs Link for ref(For Postgres) : https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToPostgreSQLInstance.html

Basically apart from the usual hostname, username, password, Initial Database/Keyspace name is also expected when connecting.
