### ISSUE TITLE
Postgressql Issue 

### ISSUE THREAD

**Issue by vontaurus** [sqlectron/sqlectron-gui#494]
Hello guys, 

I'm very, no extremely new to coding, a mix of self teaching and online lectures, and of course I have problems already. I can't connect postgresSQL to SQLectron. I am getting the user doesn't match prompt, or it is that my password is the problem. Either way I have tried to uninstall as well as completely erase from the heart of windows. If anyone can help me it would greatly appreciated.  I've been up since 2pm trying to fix this issue and it is now 5:19am 06/30/2020
Thanks

**Comment by MasterOdin** [comment]
Were you able to connect to postgres using another program and with the same credentials they fail within sqlectron? What version of postgres were you using?

**Comment by vontaurus** [comment]
Hey, thanks for getting back to me so quickly. No I wasn't able to connect
the two programs. I can't truly reset the password.

**Comment by MasterOdin** [comment]
* So you were unable to connect to postgres using another tool?
* What version of postgres are you using?
* Are you attempting to just regularly connect to it, or are you using ssh tunneling?

**Comment by MasterOdin** [comment]
closing due to lack of feedback
