### ISSUE TITLE
Tabs rendering below each other

### ISSUE THREAD

**Issue by nileplatform** [sqlectron/sqlectron-gui#509]
On the mac version 1.31.0 (1.31.0) the tabs are stacking vertically instead of horizontally.
(i installed the dmg).

<img width="1209" alt="Screenshot 2020-08-15 at 18 07 13" src="https://user-images.githubusercontent.com/67200764/90316470-bf532200-df22-11ea-82b8-f5b40cef1a68.png">

**Comment by Jiia** [comment]
Same issue, using Ubuntu 18.04

**Comment by MasterOdin** [comment]
Confirmed, will be fixed in 1.32.0 which I'm aiming to release this weekend.
