### ISSUE TITLE
sqlectron-1.31.0.sh not working 

### ISSUE THREAD

**Issue by varunsurpurkar** [sqlectron/sqlectron-gui#510]
Tried to execute the shell script version of sqlectron sqlectron-1.31.0.sh
getting 

ls: cannot access '': No such file or directory

Have Ubuntu OS

**Comment by MasterOdin** [comment]
Looked into this and filed bug upstream with electron-builder: https://github.com/electron-userland/electron-builder/issues/5285

For now, I would recommend if you wish to use the self-extracting installer (`.sh`) then you use it as `bash sqlectron-1.31.0.sh -i ~/sqlectron` and then copy the files out of `~/sqlectron/current` to your filesystem.

**Comment by MasterOdin** [comment]
Per #569, my created issue for this was auto-closed on the upstream repo so it's clearly not a priority for them to fix (or acknowledge?) so `sh` will be removed as a build output going forward. Sorry!
