### ISSUE TITLE
sqlectron-1.31.0-win not working on windows 10 32 bit os

### ISSUE THREAD

**Issue by sukansvga** [sqlectron/sqlectron-gui#523]
It's says this app can't run on your pc.
And i tried sqlectron-Setup-1.31.0.exe it's says 64-bit windows is required.
Pls help me.

**Comment by MasterOdin** [comment]
Please let me know if the .exe for the recently released 1.32.0 works for you.

**Comment by sukansvga** [comment]
Now working 👍👍👍
