### ISSUE TITLE
Update to jointjs 3.x

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sqlectron-gui#533]
Updating to jointjs 3.x as-is leads to a break in functionality. I suspect it has to do with this line from their changelog (though I'm not sure):

> * remove deprecated `PortsModelInterface` and `PortsViewInterface` from `joint.shapes.basic` [breaking change]

In any case, when upgrading to 3.x, it causes the diagram to generate blank looking boxes.

**Comment by maxcnunes** [comment]
> In any case, when upgrading to 3.x, it causes the diagram to generate blank looking boxes.

Just FYI, It was caused by the namespacing change, which needs to be defined on v3, check out the PR #664 for more details.
