### ISSUE TITLE
Dark Mode != Invert Colours

### ISSUE THREAD

**Issue by Amelia-exe** [sqlectron/sqlectron-gui#542]
Having just downloaded the latest version (v1.32.0), switching to dark mode seems to just invert the colours .... 
And to be frank, looks horrendous.

Windows 10 Home Version 2004 (OS Build 19041.572)

See images attached.
![sql1](https://user-images.githubusercontent.com/68903836/97863600-251fa080-1cff-11eb-8c2e-b09aff25d4a1.PNG)
![sql2](https://user-images.githubusercontent.com/68903836/97863688-4b454080-1cff-11eb-8188-d6b2741965a9.PNG)

**Comment by MasterOdin** [comment]
#555 improved things for sure, but there's still a lot of issues in terms of text contrast, coloring, etc. across the app that needs to be improved.

I'm going to close this issue as the core of it was fixed (dark mode is no longer an inversion), and try to open smaller tickets to address specific dark mode UI issues.
