### ISSUE TITLE
Upgrade Electron 10

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#550]
This will help us keep up to date with all the improvements done to Electron.

**Comment by MasterOdin** [comment]
Will need to move to the newest version of the sqlite3 library (5.0.1), which breaks compatibility for node < 10. Additionally, given some of the bug reports there, it's not totally clear if moving to 10 will work, or if 9 is as high as we could go and make sure that `allowRendererReuse` is false.
