### ISSUE TITLE
Ed25519 / ECDSA ssh keys not supported for SSH tunneled connections

### ISSUE THREAD

**Issue by dsecareanu** [sqlectron/sqlectron-gui#559]
Hi there,

It seems that Ed25519 / ECDSA ssh keys are not supported for SSH tunneled connections:

Connection Error
Cannot parse privateKey: Unsupported key format

Sqlelectron 1.32.1
MacOS BigSur 11.1

Thanks.

Reference:
https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54

**Comment by yi-mei-wang** [comment]
@dsecareanu I'm facing the issue. Did you manage to find a solution for this?

**Comment by maxcnunes** [comment]
Closing this because it is duplicated of https://github.com/sqlectron/sqlectron-gui/issues/559
