### ISSUE TITLE
Blank Screen Make App Unusable

### ISSUE THREAD

**Issue by luizfelipevbll** [sqlectron/sqlectron-gui#573]
Some querys when performed causes the app to crash, also running CTRL+R or CTRL+ENTER have the same problem sometimes.
I am using Linux POP!_OS 20.04 LTS, but I have the same problem on a Windows 10 machine too.
![image](https://user-images.githubusercontent.com/40257388/108998714-124f2400-7680-11eb-8424-ba0ded5e8420.png)
![image](https://user-images.githubusercontent.com/40257388/108998753-1f6c1300-7680-11eb-885f-ad8f81376b4f.png)

**Comment by MasterOdin** [comment]
Just to make things a bit easier for me, would you mind sharing what database adapter you're using (e.g. mysql, sqlserver, etc.)?

**Comment by luizfelipevbll** [comment]
> Just to make things a bit easier for me, would you mind sharing what database adapter you're using (e.g. mysql, sqlserver, etc.)?


I have MariaDB and SQLServer databases, the problem occurs on both adapters.

**Comment by Vimugdh** [comment]
"use" as well as "alter table" are causing this issue (so far). The query executes though. When I open a new window and reconnect, the table is correctly modified. I'm using MySQL DB on a Windows 10 machine.

**Comment by maxcnunes** [comment]
I just noticed this happening for LOCK TABLES on MySQL as well.

**Comment by MasterOdin** [comment]
I think I've figured this out, and should be fixed in the next release.
