### ISSUE TITLE
Database list under dark mode uses black text

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sqlectron-gui#583]
<img width="807" alt="Screen Shot 2021-03-01 at 9 48 05 AM" src="https://user-images.githubusercontent.com/1845314/109513566-3d1bec80-7a73-11eb-9066-6b9e0ffb11c3.png">

<img width="1027" alt="Screen Shot 2021-03-01 at 9 47 20 AM" src="https://user-images.githubusercontent.com/1845314/109513486-283f5900-7a73-11eb-9e21-07bfde910462.png">

**Comment by ma3ve** [comment]
I have worked on this issue and create a PR. #606

**Comment by MasterOdin** [comment]
Fixed in 06a0e0f
