### ISSUE TITLE
Long table names exceed left pane width

### ISSUE THREAD

**Issue by RaffaeleT** [sqlectron/sqlectron-gui#60]
A minor aesthetic flaw.
eg "account_analytic_analysis_summary_month"  exceeds over the boundary of the left pane.
Left pane should have resizable width.

**Comment by maxcnunes** [comment]
Fixed on commits: faa6f99a6140c992a145dc6c5d27adae8d7b6239 and faa6f99a6140c992a145dc6c5d27adae8d7b6239
