### ISSUE TITLE
Running that app in dev mode with sqlectron-db-core linked from source isn't working

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#603]
It seems to be failing because of some typescript issue.

**Comment by maxcnunes** [comment]
@MasterOdin because we publish only the contents of dist folder making that the root directory, when we are in development linked to sqlectron-db-core from source the files are not in the root but in the dist folder. Which breaks the module loading for imports like this `sqlectron-db-core/adapters/abstract_adapter`, since local compile it is placed at `sqlectron-db-core/dist/adapters/abstract_adapter`. I have tried to use `paths` configuration from tsconfig to resolve both path options, but it didn't work. I think we are gonna need to make everything exported by the index file so we don't need to access any module by sub paths. Do you have any other idea?

**Comment by MasterOdin** [comment]
Should be doable to just increase the number of top-level exports from `sqlectron-db-core`. Will need to first draw up a list of what all we need to lift up out of the it.
