### ISSUE TITLE
Add storybook to make easier out of app component styling

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sqlectron-gui#626]
Playing with [storybook](https://storybook.js.org/) lately and it's been super useful to help in doing UI work on components in a nice isolated fashion from the rest of the app. There was some set-up in https://github.com/sqlectron/sqlectron-gui/pull/553, and so can use that as a base for adding it here. To start, will only focus on getting it done for the [checkbox component](https://github.com/sqlectron/sqlectron-gui/blob/main/src/renderer/components/checkbox.tsx) as it's very simple and does not have any sort of complex chain we might need to mock out.

The one question I have is on preferred structure @maxcnunes. Do we want the stories to live in their own folder that's separate from source code (or within the source code folder) such as `./stories` or `./src/renderer/components/stories` or ..., or just place the stories immediately next to the component, like:

```
* ./src/renderer/components/checkbox.tsx
* ./src/renderer/components/checkbox.stories.tsx
```

I kind of like the latter as it makes it easy to find and how it works in my dayjob, but happy to go with alternatives.

**Comment by maxcnunes** [comment]
I am fine with either options.

That would be quite helpful once we start working on https://github.com/sqlectron/sqlectron-gui/issues/546 and better supporting dark theme.
