### ISSUE TITLE
Feature to enable editing the table.

### ISSUE THREAD

**Issue by dev-rsonx** [sqlectron/sqlectron-gui#636]
It would be great if there is a feature to edit the table's row on the go like in excel, rather than having to execute a ALTER TABLE command.

**Comment by maxcnunes** [comment]
Yes, we plan to support that, but didn't have the time to implement it yet =/ Btw, I am closing this ticket, because it is duplicated https://github.com/sqlectron/sqlectron-gui/issues/275
