### ISSUE TITLE
Can't input text on editor after a query without clicking discard

### ISSUE THREAD

**Issue by betafcc** [sqlectron/sqlectron-gui#646]
After executing a query, the editor becomes irresponsive for inputting text, somehow the backspace does work:

![bug (7)](https://user-images.githubusercontent.com/27316303/116953620-02f6e300-ac8e-11eb-9b6f-2126c8acbf15.gif)

### Environment
- Sqlectron 1.36.0
- MacOS Big Sur
- Bare mysql:8 from docker image (just run `docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password mysql:8`)
- full config file:
```json
{
  "servers": [
    {
      "id": "cb508927-9f47-41b7-b457-150425a2045a",
      "name": "mysql",
      "client": "mysql",
      "ssl": false,
      "host": "localhost",
      "port": 3306,
      "socketPath": null,
      "user": "root",
      "password": {
        "ivText": "6lv2/JcFt9rMLiANclLr0A==",
        "encryptedText": "GIYgFDGkmI0ZuYBBdK8Prg=="
      },
      "schema": null,
      "encrypted": true
    }
  ],
  "zoomFactor": 1,
  "limitQueryDefaultSelectTop": 100,
  "enabledAutoComplete": false,
  "enabledDarkTheme": false,
  "disabledOpenAnimation": true,
  "csvDelimiter": ",",
  "connectionsAsList": false,
  "customFont": "Lato",
  "log": {
    "console": true,
    "file": false,
    "level": "error",
    "path": "/Users/brendon.faccion/Library/Preferences/Sqlectron/sqlectron.log"
  },
  "enabledLiveAutoComplete": false
}
```

### Steps to reproduce:

1 - Set up mysql db with `docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password mysql:8`
2 - Open sqlectron and connect to it
3 - Click on the `mysql` db, then the `db` table
4 - Edit the auto-generated query from `LIMIT 100` to `LIMIT 2` to confirm the editor works and run it
5 - Try to change `LIMIT 2` to `LIMIT 1`

You should fail to input text although the backspace does work.
After clicking `discard` the editor does come back to normal.

**Comment by maxcnunes** [comment]
I noticed that too recently but forgot to open a ticket for it, so thanks for reporting it.
While we don't have a proper fixing for it, the workaround I have been using is clicking on the tab title, it seems to unlock the text editor after that.

**Comment by Kos-M** [comment]
You can continue edit , if you click anywhere outside inout area, for example in result rows , and then click/focus on input again.
This is fefinately a bug, but i think it has relation with focus , something is block edit..

**Comment by sandro** [comment]
I use `CMD-f` to bring up the finder dialog, which restores input.

**Comment by sveneh** [comment]
This is still happening in the current version v1.37.1 . It is quite annoying.
