### ISSUE TITLE
"sqlelectron" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by gitowiec** [sqlectron/sqlectron-gui#669]
So I am new to Mac and here is this popup. How to run sqlelectron?
<img width="342" alt="Screenshot 2021-06-15 at 10 58 28" src="https://user-images.githubusercontent.com/1553195/122024561-d5db3b80-cdc8-11eb-875b-6d6554a2ccf0.png">

**Comment by adriankarlen** [comment]
If you go to the app in finder, _right click_ and click _open_ in the menu instead, you should now see an open alternative in the popup aswell.

**Comment by MasterOdin** [comment]
This has been added in 641dfee327329625ddad2b52ebc71afaeab2c7bd and b4886b9ae5a1b1ebe730662e55c0d7bd97984380 and will be available in the next release which should hopefully be this week.
