### ISSUE TITLE
Error: MSSQL - Cannot Read Property Rowcount of Undefined

### ISSUE THREAD

**Issue by saitolabs** [sqlectron/sqlectron-gui#71]
Why that message when I try to execute this select statement?

![cannot_read_property_rowcount_of_undefined](https://cloud.githubusercontent.com/assets/1012457/11790427/e179d086-a282-11e5-99ff-f0a145ce479f.png)

**Comment by maxcnunes** [comment]
Does this problem occurs without the brackets? By the way, what is the reason of the brackets, I guess I have never seen brackets in a SQL query before :smile: .

**Comment by saitolabs** [comment]
This problem still occurs without the brackets :(

I just did double clicked the table name. After that, the select statement appeared.
Btw it's a common practice to use brackets, maybe because Microsoft SQL Server Management Studio use brackets as default.
