### ISSUE TITLE
SSL Mode

### ISSUE THREAD

**Issue by corbanb** [sqlectron/sqlectron-gui#72]
Currently there seems to be no way to connect to a heroku postgres db due to ssl mode. I tried adding the query param `?sslmode=require` to the url but no luck. Any thoughts on how this might be accomplished?

**Comment by maxcnunes** [comment]
Humm. We are not setting the ssl attribute ([current configuration](https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/postgresql.js#L173) and [example postgresql with ssl](https://github.com/brianc/node-postgres/blob/35e5567f86774f808c2a8518dd312b8aa3586693/test/integration/client/heroku-ssl-tests.js#L15)) to the db connection configuration.

We gonna need a new button in the interface to enable the SSL support and pass this configuration ahead until the sqlectron-core.

I guess I can take a look on this today.
