### ISSUE TITLE
Option to disable intro animation

### ISSUE THREAD

**Issue by Nimja** [sqlectron/sqlectron-gui#728]
As awesome as the intro animation is, it is not fun to have one every time you open a new window. It'd be nice to turn it off and just see the logo, without any animation, loading as quickly as possible.

To reproduce, open a new window with Ctrl + N (Windows/Linux) or Cmd + N (Mac)

**Comment by mtcnxd** [comment]
The animation option can be disabled from the settings

**Comment by Nimja** [comment]
Confirmed, works as expected.

Settings: Disable Intro.
