### ISSUE TITLE
No response from configure window using MySQL 5.7.10

### ISSUE THREAD

**Issue by andywenk** [sqlectron/sqlectron-gui#77]
I am trying to connect to a local MySQL database (Version: '5.7.10'  socket: '/tmp/mysql.sock'  port: 3306  Homebrew). When opening the configuration view I added everything needed (see screenshot)

<img width="1031" alt="screen shot 2015-12-23 at 13 35 47" src="https://cloud.githubusercontent.com/assets/51517/11976608/19816d56-a97a-11e5-80ed-68e0fdbb210f.png">

when clicking the "Save" button nothing happens. I also don't see any output in the DevTools panel. The ~/.sqlectron.json file does not have servers:

     {
       "servers": []
     }

What am I doing wrong? 

Version 1.2.0 (1.2.0)

Info: I just upgraded to MySQL 5.7.10 and I have now trouble to connect to the same database with Sequel Pro also. So maybe this is not a sqlectron problem but worth investigating.

**Comment by maxcnunes** [comment]
That is weird. The connection is working here.
```
mysql  Ver 14.14 Distrib 5.7.10, for Linux (x86_64) using  EditLine wrapper
```
Although I really can't create a new server connection if I don't check the SSL option.
This way works:
![screen shot 2015-12-23 at 2 46 26 pm](https://cloud.githubusercontent.com/assets/680356/11980750/3ac75a02-a984-11e5-9c22-38022d4d2a7d.png)

> My MySQL server is not running locally but it should not differs from yours.

What is weirder is that after creating the server connection with SSL enabled I'm able to edit it to SSL disabled.

I guess it is an workaround you can use for now. I'm going to take a look in this problem later, probably is just some misunderstanding in the validation.

**Comment by andywenk** [comment]
ok I'll grab master and build it to see if it's working ;-) Thanks
