### ISSUE TITLE
Fails to launch on fresh install Windows 10

### ISSUE THREAD

**Issue by jasonCodesAway** [sqlectron/sqlectron-gui#78]
Most recent version (Sqlectron-win32-x64.zip version 1.2.0) crashes on trying to start it up. There was no visible error, it just wouldn't start after being installed. I managed to find this crash folder (zipped & attached here).
[Sqlectron Crashes.zip](https://github.com/sqlectron/sqlectron-gui/files/71913/Sqlectron.Crashes.zip)

**Comment by maxcnunes** [comment]
I have just tested on Windows 8 and it is working. I can take a look on that using Windows 10 only after 01/04. When I get back to my place where there is a much better internet to download a VM with Windows 10. :sob: 
By the way, have you tried running it with Windows 8 compatibility? It might work. :pray:

**Comment by jasonCodesAway** [comment]
Nice suggestion on compatibility mode, I should've tried that. I just tried it though and I was hopeful but alas it didn't change the behavior :(

**Comment by maxcnunes** [comment]
I guess was a problem during the build for windows. I have released a new version  https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.3.0 and its working on my VM with windows 10. Please @jasonCodesAway, could you check it out?

**Comment by maxcnunes** [comment]
Closing it now. Let me know if you find any problem.

**Comment by jasonCodesAway** [comment]
Sorry I was on back-to-back business trips. It works!!! Thank you :)
